// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker_service.proto

#ifndef PROTOBUF_INCLUDED_worker_5fservice_2eproto
#define PROTOBUF_INCLUDED_worker_5fservice_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/empty.pb.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_worker_5fservice_2eproto 

namespace protobuf_worker_5fservice_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[5];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_worker_5fservice_2eproto
namespace mapreduce {
class MapJob;
class MapJobDefaultTypeInternal;
extern MapJobDefaultTypeInternal _MapJob_default_instance_;
class MapJob_MapKV;
class MapJob_MapKVDefaultTypeInternal;
extern MapJob_MapKVDefaultTypeInternal _MapJob_MapKV_default_instance_;
class ReduceJob;
class ReduceJobDefaultTypeInternal;
extern ReduceJobDefaultTypeInternal _ReduceJob_default_instance_;
class ReduceJob_ReduceKV;
class ReduceJob_ReduceKVDefaultTypeInternal;
extern ReduceJob_ReduceKVDefaultTypeInternal _ReduceJob_ReduceKV_default_instance_;
class WorkerReplyMsg;
class WorkerReplyMsgDefaultTypeInternal;
extern WorkerReplyMsgDefaultTypeInternal _WorkerReplyMsg_default_instance_;
}  // namespace mapreduce
namespace google {
namespace protobuf {
template<> ::mapreduce::MapJob* Arena::CreateMaybeMessage<::mapreduce::MapJob>(Arena*);
template<> ::mapreduce::MapJob_MapKV* Arena::CreateMaybeMessage<::mapreduce::MapJob_MapKV>(Arena*);
template<> ::mapreduce::ReduceJob* Arena::CreateMaybeMessage<::mapreduce::ReduceJob>(Arena*);
template<> ::mapreduce::ReduceJob_ReduceKV* Arena::CreateMaybeMessage<::mapreduce::ReduceJob_ReduceKV>(Arena*);
template<> ::mapreduce::WorkerReplyMsg* Arena::CreateMaybeMessage<::mapreduce::WorkerReplyMsg>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace mapreduce {

enum WorkerReplyMsg_WorkerState {
  WorkerReplyMsg_WorkerState_UNKNOWN = 0,
  WorkerReplyMsg_WorkerState_INIT = 1,
  WorkerReplyMsg_WorkerState_IDLE = 2,
  WorkerReplyMsg_WorkerState_WORKING = 3,
  WorkerReplyMsg_WorkerState_CLOSE = 4,
  WorkerReplyMsg_WorkerState_WorkerReplyMsg_WorkerState_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  WorkerReplyMsg_WorkerState_WorkerReplyMsg_WorkerState_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool WorkerReplyMsg_WorkerState_IsValid(int value);
const WorkerReplyMsg_WorkerState WorkerReplyMsg_WorkerState_WorkerState_MIN = WorkerReplyMsg_WorkerState_UNKNOWN;
const WorkerReplyMsg_WorkerState WorkerReplyMsg_WorkerState_WorkerState_MAX = WorkerReplyMsg_WorkerState_CLOSE;
const int WorkerReplyMsg_WorkerState_WorkerState_ARRAYSIZE = WorkerReplyMsg_WorkerState_WorkerState_MAX + 1;

const ::google::protobuf::EnumDescriptor* WorkerReplyMsg_WorkerState_descriptor();
inline const ::std::string& WorkerReplyMsg_WorkerState_Name(WorkerReplyMsg_WorkerState value) {
  return ::google::protobuf::internal::NameOfEnum(
    WorkerReplyMsg_WorkerState_descriptor(), value);
}
inline bool WorkerReplyMsg_WorkerState_Parse(
    const ::std::string& name, WorkerReplyMsg_WorkerState* value) {
  return ::google::protobuf::internal::ParseNamedEnum<WorkerReplyMsg_WorkerState>(
    WorkerReplyMsg_WorkerState_descriptor(), name, value);
}
// ===================================================================

class WorkerReplyMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mapreduce.WorkerReplyMsg) */ {
 public:
  WorkerReplyMsg();
  virtual ~WorkerReplyMsg();

  WorkerReplyMsg(const WorkerReplyMsg& from);

  inline WorkerReplyMsg& operator=(const WorkerReplyMsg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  WorkerReplyMsg(WorkerReplyMsg&& from) noexcept
    : WorkerReplyMsg() {
    *this = ::std::move(from);
  }

  inline WorkerReplyMsg& operator=(WorkerReplyMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const WorkerReplyMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WorkerReplyMsg* internal_default_instance() {
    return reinterpret_cast<const WorkerReplyMsg*>(
               &_WorkerReplyMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(WorkerReplyMsg* other);
  friend void swap(WorkerReplyMsg& a, WorkerReplyMsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline WorkerReplyMsg* New() const final {
    return CreateMaybeMessage<WorkerReplyMsg>(NULL);
  }

  WorkerReplyMsg* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<WorkerReplyMsg>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const WorkerReplyMsg& from);
  void MergeFrom(const WorkerReplyMsg& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WorkerReplyMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef WorkerReplyMsg_WorkerState WorkerState;
  static const WorkerState UNKNOWN =
    WorkerReplyMsg_WorkerState_UNKNOWN;
  static const WorkerState INIT =
    WorkerReplyMsg_WorkerState_INIT;
  static const WorkerState IDLE =
    WorkerReplyMsg_WorkerState_IDLE;
  static const WorkerState WORKING =
    WorkerReplyMsg_WorkerState_WORKING;
  static const WorkerState CLOSE =
    WorkerReplyMsg_WorkerState_CLOSE;
  static inline bool WorkerState_IsValid(int value) {
    return WorkerReplyMsg_WorkerState_IsValid(value);
  }
  static const WorkerState WorkerState_MIN =
    WorkerReplyMsg_WorkerState_WorkerState_MIN;
  static const WorkerState WorkerState_MAX =
    WorkerReplyMsg_WorkerState_WorkerState_MAX;
  static const int WorkerState_ARRAYSIZE =
    WorkerReplyMsg_WorkerState_WorkerState_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  WorkerState_descriptor() {
    return WorkerReplyMsg_WorkerState_descriptor();
  }
  static inline const ::std::string& WorkerState_Name(WorkerState value) {
    return WorkerReplyMsg_WorkerState_Name(value);
  }
  static inline bool WorkerState_Parse(const ::std::string& name,
      WorkerState* value) {
    return WorkerReplyMsg_WorkerState_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // string msg = 2;
  void clear_msg();
  static const int kMsgFieldNumber = 2;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_msg(::std::string&& value);
  #endif
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // bool ok = 1;
  void clear_ok();
  static const int kOkFieldNumber = 1;
  bool ok() const;
  void set_ok(bool value);

  // .mapreduce.WorkerReplyMsg.WorkerState state = 3;
  void clear_state();
  static const int kStateFieldNumber = 3;
  ::mapreduce::WorkerReplyMsg_WorkerState state() const;
  void set_state(::mapreduce::WorkerReplyMsg_WorkerState value);

  // @@protoc_insertion_point(class_scope:mapreduce.WorkerReplyMsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  bool ok_;
  int state_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_worker_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MapJob_MapKV : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mapreduce.MapJob.MapKV) */ {
 public:
  MapJob_MapKV();
  virtual ~MapJob_MapKV();

  MapJob_MapKV(const MapJob_MapKV& from);

  inline MapJob_MapKV& operator=(const MapJob_MapKV& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MapJob_MapKV(MapJob_MapKV&& from) noexcept
    : MapJob_MapKV() {
    *this = ::std::move(from);
  }

  inline MapJob_MapKV& operator=(MapJob_MapKV&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MapJob_MapKV& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MapJob_MapKV* internal_default_instance() {
    return reinterpret_cast<const MapJob_MapKV*>(
               &_MapJob_MapKV_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(MapJob_MapKV* other);
  friend void swap(MapJob_MapKV& a, MapJob_MapKV& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MapJob_MapKV* New() const final {
    return CreateMaybeMessage<MapJob_MapKV>(NULL);
  }

  MapJob_MapKV* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MapJob_MapKV>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MapJob_MapKV& from);
  void MergeFrom(const MapJob_MapKV& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MapJob_MapKV* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string key = 1;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  #if LANG_CXX11
  void set_key(::std::string&& value);
  #endif
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // string value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:mapreduce.MapJob.MapKV)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_worker_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MapJob : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mapreduce.MapJob) */ {
 public:
  MapJob();
  virtual ~MapJob();

  MapJob(const MapJob& from);

  inline MapJob& operator=(const MapJob& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MapJob(MapJob&& from) noexcept
    : MapJob() {
    *this = ::std::move(from);
  }

  inline MapJob& operator=(MapJob&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MapJob& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MapJob* internal_default_instance() {
    return reinterpret_cast<const MapJob*>(
               &_MapJob_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(MapJob* other);
  friend void swap(MapJob& a, MapJob& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MapJob* New() const final {
    return CreateMaybeMessage<MapJob>(NULL);
  }

  MapJob* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MapJob>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MapJob& from);
  void MergeFrom(const MapJob& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MapJob* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef MapJob_MapKV MapKV;

  // accessors -------------------------------------------------------

  // repeated .mapreduce.MapJob.MapKV map_kvs = 5;
  int map_kvs_size() const;
  void clear_map_kvs();
  static const int kMapKvsFieldNumber = 5;
  ::mapreduce::MapJob_MapKV* mutable_map_kvs(int index);
  ::google::protobuf::RepeatedPtrField< ::mapreduce::MapJob_MapKV >*
      mutable_map_kvs();
  const ::mapreduce::MapJob_MapKV& map_kvs(int index) const;
  ::mapreduce::MapJob_MapKV* add_map_kvs();
  const ::google::protobuf::RepeatedPtrField< ::mapreduce::MapJob_MapKV >&
      map_kvs() const;

  // string name = 3;
  void clear_name();
  static const int kNameFieldNumber = 3;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // string type = 4;
  void clear_type();
  static const int kTypeFieldNumber = 4;
  const ::std::string& type() const;
  void set_type(const ::std::string& value);
  #if LANG_CXX11
  void set_type(::std::string&& value);
  #endif
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  ::std::string* mutable_type();
  ::std::string* release_type();
  void set_allocated_type(::std::string* type);

  // uint32 job_id = 1;
  void clear_job_id();
  static const int kJobIdFieldNumber = 1;
  ::google::protobuf::uint32 job_id() const;
  void set_job_id(::google::protobuf::uint32 value);

  // uint32 sub_job_id = 2;
  void clear_sub_job_id();
  static const int kSubJobIdFieldNumber = 2;
  ::google::protobuf::uint32 sub_job_id() const;
  void set_sub_job_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:mapreduce.MapJob)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::mapreduce::MapJob_MapKV > map_kvs_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr type_;
  ::google::protobuf::uint32 job_id_;
  ::google::protobuf::uint32 sub_job_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_worker_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReduceJob_ReduceKV : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mapreduce.ReduceJob.ReduceKV) */ {
 public:
  ReduceJob_ReduceKV();
  virtual ~ReduceJob_ReduceKV();

  ReduceJob_ReduceKV(const ReduceJob_ReduceKV& from);

  inline ReduceJob_ReduceKV& operator=(const ReduceJob_ReduceKV& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReduceJob_ReduceKV(ReduceJob_ReduceKV&& from) noexcept
    : ReduceJob_ReduceKV() {
    *this = ::std::move(from);
  }

  inline ReduceJob_ReduceKV& operator=(ReduceJob_ReduceKV&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReduceJob_ReduceKV& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReduceJob_ReduceKV* internal_default_instance() {
    return reinterpret_cast<const ReduceJob_ReduceKV*>(
               &_ReduceJob_ReduceKV_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(ReduceJob_ReduceKV* other);
  friend void swap(ReduceJob_ReduceKV& a, ReduceJob_ReduceKV& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReduceJob_ReduceKV* New() const final {
    return CreateMaybeMessage<ReduceJob_ReduceKV>(NULL);
  }

  ReduceJob_ReduceKV* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReduceJob_ReduceKV>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReduceJob_ReduceKV& from);
  void MergeFrom(const ReduceJob_ReduceKV& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReduceJob_ReduceKV* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string value = 2;
  int value_size() const;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value(int index) const;
  ::std::string* mutable_value(int index);
  void set_value(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_value(int index, ::std::string&& value);
  #endif
  void set_value(int index, const char* value);
  void set_value(int index, const char* value, size_t size);
  ::std::string* add_value();
  void add_value(const ::std::string& value);
  #if LANG_CXX11
  void add_value(::std::string&& value);
  #endif
  void add_value(const char* value);
  void add_value(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& value() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_value();

  // string key = 1;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  #if LANG_CXX11
  void set_key(::std::string&& value);
  #endif
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // @@protoc_insertion_point(class_scope:mapreduce.ReduceJob.ReduceKV)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> value_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_worker_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReduceJob : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mapreduce.ReduceJob) */ {
 public:
  ReduceJob();
  virtual ~ReduceJob();

  ReduceJob(const ReduceJob& from);

  inline ReduceJob& operator=(const ReduceJob& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReduceJob(ReduceJob&& from) noexcept
    : ReduceJob() {
    *this = ::std::move(from);
  }

  inline ReduceJob& operator=(ReduceJob&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReduceJob& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReduceJob* internal_default_instance() {
    return reinterpret_cast<const ReduceJob*>(
               &_ReduceJob_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(ReduceJob* other);
  friend void swap(ReduceJob& a, ReduceJob& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReduceJob* New() const final {
    return CreateMaybeMessage<ReduceJob>(NULL);
  }

  ReduceJob* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReduceJob>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReduceJob& from);
  void MergeFrom(const ReduceJob& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReduceJob* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef ReduceJob_ReduceKV ReduceKV;

  // accessors -------------------------------------------------------

  // repeated .mapreduce.ReduceJob.ReduceKV reduce_kvs = 5;
  int reduce_kvs_size() const;
  void clear_reduce_kvs();
  static const int kReduceKvsFieldNumber = 5;
  ::mapreduce::ReduceJob_ReduceKV* mutable_reduce_kvs(int index);
  ::google::protobuf::RepeatedPtrField< ::mapreduce::ReduceJob_ReduceKV >*
      mutable_reduce_kvs();
  const ::mapreduce::ReduceJob_ReduceKV& reduce_kvs(int index) const;
  ::mapreduce::ReduceJob_ReduceKV* add_reduce_kvs();
  const ::google::protobuf::RepeatedPtrField< ::mapreduce::ReduceJob_ReduceKV >&
      reduce_kvs() const;

  // string name = 3;
  void clear_name();
  static const int kNameFieldNumber = 3;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // string type = 4;
  void clear_type();
  static const int kTypeFieldNumber = 4;
  const ::std::string& type() const;
  void set_type(const ::std::string& value);
  #if LANG_CXX11
  void set_type(::std::string&& value);
  #endif
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  ::std::string* mutable_type();
  ::std::string* release_type();
  void set_allocated_type(::std::string* type);

  // uint32 job_id = 1;
  void clear_job_id();
  static const int kJobIdFieldNumber = 1;
  ::google::protobuf::uint32 job_id() const;
  void set_job_id(::google::protobuf::uint32 value);

  // uint32 sub_job_id = 2;
  void clear_sub_job_id();
  static const int kSubJobIdFieldNumber = 2;
  ::google::protobuf::uint32 sub_job_id() const;
  void set_sub_job_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:mapreduce.ReduceJob)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::mapreduce::ReduceJob_ReduceKV > reduce_kvs_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr type_;
  ::google::protobuf::uint32 job_id_;
  ::google::protobuf::uint32 sub_job_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_worker_5fservice_2eproto::TableStruct;
};
// ===================================================================

class WorkerService_Stub;

class WorkerService : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline WorkerService() {};
 public:
  virtual ~WorkerService();

  typedef WorkerService_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void Beat(::google::protobuf::RpcController* controller,
                       const ::google::protobuf::Empty* request,
                       ::mapreduce::WorkerReplyMsg* response,
                       ::google::protobuf::Closure* done);
  virtual void Map(::google::protobuf::RpcController* controller,
                       const ::mapreduce::MapJob* request,
                       ::mapreduce::WorkerReplyMsg* response,
                       ::google::protobuf::Closure* done);
  virtual void Reduce(::google::protobuf::RpcController* controller,
                       const ::mapreduce::ReduceJob* request,
                       ::mapreduce::WorkerReplyMsg* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(WorkerService);
};

class WorkerService_Stub : public WorkerService {
 public:
  WorkerService_Stub(::google::protobuf::RpcChannel* channel);
  WorkerService_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~WorkerService_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements WorkerService ------------------------------------------

  void Beat(::google::protobuf::RpcController* controller,
                       const ::google::protobuf::Empty* request,
                       ::mapreduce::WorkerReplyMsg* response,
                       ::google::protobuf::Closure* done);
  void Map(::google::protobuf::RpcController* controller,
                       const ::mapreduce::MapJob* request,
                       ::mapreduce::WorkerReplyMsg* response,
                       ::google::protobuf::Closure* done);
  void Reduce(::google::protobuf::RpcController* controller,
                       const ::mapreduce::ReduceJob* request,
                       ::mapreduce::WorkerReplyMsg* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(WorkerService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// WorkerReplyMsg

// bool ok = 1;
inline void WorkerReplyMsg::clear_ok() {
  ok_ = false;
}
inline bool WorkerReplyMsg::ok() const {
  // @@protoc_insertion_point(field_get:mapreduce.WorkerReplyMsg.ok)
  return ok_;
}
inline void WorkerReplyMsg::set_ok(bool value) {
  
  ok_ = value;
  // @@protoc_insertion_point(field_set:mapreduce.WorkerReplyMsg.ok)
}

// string msg = 2;
inline void WorkerReplyMsg::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& WorkerReplyMsg::msg() const {
  // @@protoc_insertion_point(field_get:mapreduce.WorkerReplyMsg.msg)
  return msg_.GetNoArena();
}
inline void WorkerReplyMsg::set_msg(const ::std::string& value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mapreduce.WorkerReplyMsg.msg)
}
#if LANG_CXX11
inline void WorkerReplyMsg::set_msg(::std::string&& value) {
  
  msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mapreduce.WorkerReplyMsg.msg)
}
#endif
inline void WorkerReplyMsg::set_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mapreduce.WorkerReplyMsg.msg)
}
inline void WorkerReplyMsg::set_msg(const char* value, size_t size) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mapreduce.WorkerReplyMsg.msg)
}
inline ::std::string* WorkerReplyMsg::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:mapreduce.WorkerReplyMsg.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* WorkerReplyMsg::release_msg() {
  // @@protoc_insertion_point(field_release:mapreduce.WorkerReplyMsg.msg)
  
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WorkerReplyMsg::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:mapreduce.WorkerReplyMsg.msg)
}

// .mapreduce.WorkerReplyMsg.WorkerState state = 3;
inline void WorkerReplyMsg::clear_state() {
  state_ = 0;
}
inline ::mapreduce::WorkerReplyMsg_WorkerState WorkerReplyMsg::state() const {
  // @@protoc_insertion_point(field_get:mapreduce.WorkerReplyMsg.state)
  return static_cast< ::mapreduce::WorkerReplyMsg_WorkerState >(state_);
}
inline void WorkerReplyMsg::set_state(::mapreduce::WorkerReplyMsg_WorkerState value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:mapreduce.WorkerReplyMsg.state)
}

// -------------------------------------------------------------------

// MapJob_MapKV

// string key = 1;
inline void MapJob_MapKV::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MapJob_MapKV::key() const {
  // @@protoc_insertion_point(field_get:mapreduce.MapJob.MapKV.key)
  return key_.GetNoArena();
}
inline void MapJob_MapKV::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mapreduce.MapJob.MapKV.key)
}
#if LANG_CXX11
inline void MapJob_MapKV::set_key(::std::string&& value) {
  
  key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mapreduce.MapJob.MapKV.key)
}
#endif
inline void MapJob_MapKV::set_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mapreduce.MapJob.MapKV.key)
}
inline void MapJob_MapKV::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mapreduce.MapJob.MapKV.key)
}
inline ::std::string* MapJob_MapKV::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:mapreduce.MapJob.MapKV.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MapJob_MapKV::release_key() {
  // @@protoc_insertion_point(field_release:mapreduce.MapJob.MapKV.key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MapJob_MapKV::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:mapreduce.MapJob.MapKV.key)
}

// string value = 2;
inline void MapJob_MapKV::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MapJob_MapKV::value() const {
  // @@protoc_insertion_point(field_get:mapreduce.MapJob.MapKV.value)
  return value_.GetNoArena();
}
inline void MapJob_MapKV::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mapreduce.MapJob.MapKV.value)
}
#if LANG_CXX11
inline void MapJob_MapKV::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mapreduce.MapJob.MapKV.value)
}
#endif
inline void MapJob_MapKV::set_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mapreduce.MapJob.MapKV.value)
}
inline void MapJob_MapKV::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mapreduce.MapJob.MapKV.value)
}
inline ::std::string* MapJob_MapKV::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:mapreduce.MapJob.MapKV.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MapJob_MapKV::release_value() {
  // @@protoc_insertion_point(field_release:mapreduce.MapJob.MapKV.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MapJob_MapKV::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:mapreduce.MapJob.MapKV.value)
}

// -------------------------------------------------------------------

// MapJob

// uint32 job_id = 1;
inline void MapJob::clear_job_id() {
  job_id_ = 0u;
}
inline ::google::protobuf::uint32 MapJob::job_id() const {
  // @@protoc_insertion_point(field_get:mapreduce.MapJob.job_id)
  return job_id_;
}
inline void MapJob::set_job_id(::google::protobuf::uint32 value) {
  
  job_id_ = value;
  // @@protoc_insertion_point(field_set:mapreduce.MapJob.job_id)
}

// uint32 sub_job_id = 2;
inline void MapJob::clear_sub_job_id() {
  sub_job_id_ = 0u;
}
inline ::google::protobuf::uint32 MapJob::sub_job_id() const {
  // @@protoc_insertion_point(field_get:mapreduce.MapJob.sub_job_id)
  return sub_job_id_;
}
inline void MapJob::set_sub_job_id(::google::protobuf::uint32 value) {
  
  sub_job_id_ = value;
  // @@protoc_insertion_point(field_set:mapreduce.MapJob.sub_job_id)
}

// string name = 3;
inline void MapJob::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MapJob::name() const {
  // @@protoc_insertion_point(field_get:mapreduce.MapJob.name)
  return name_.GetNoArena();
}
inline void MapJob::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mapreduce.MapJob.name)
}
#if LANG_CXX11
inline void MapJob::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mapreduce.MapJob.name)
}
#endif
inline void MapJob::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mapreduce.MapJob.name)
}
inline void MapJob::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mapreduce.MapJob.name)
}
inline ::std::string* MapJob::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:mapreduce.MapJob.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MapJob::release_name() {
  // @@protoc_insertion_point(field_release:mapreduce.MapJob.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MapJob::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:mapreduce.MapJob.name)
}

// string type = 4;
inline void MapJob::clear_type() {
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MapJob::type() const {
  // @@protoc_insertion_point(field_get:mapreduce.MapJob.type)
  return type_.GetNoArena();
}
inline void MapJob::set_type(const ::std::string& value) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mapreduce.MapJob.type)
}
#if LANG_CXX11
inline void MapJob::set_type(::std::string&& value) {
  
  type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mapreduce.MapJob.type)
}
#endif
inline void MapJob::set_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mapreduce.MapJob.type)
}
inline void MapJob::set_type(const char* value, size_t size) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mapreduce.MapJob.type)
}
inline ::std::string* MapJob::mutable_type() {
  
  // @@protoc_insertion_point(field_mutable:mapreduce.MapJob.type)
  return type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MapJob::release_type() {
  // @@protoc_insertion_point(field_release:mapreduce.MapJob.type)
  
  return type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MapJob::set_allocated_type(::std::string* type) {
  if (type != NULL) {
    
  } else {
    
  }
  type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:mapreduce.MapJob.type)
}

// repeated .mapreduce.MapJob.MapKV map_kvs = 5;
inline int MapJob::map_kvs_size() const {
  return map_kvs_.size();
}
inline void MapJob::clear_map_kvs() {
  map_kvs_.Clear();
}
inline ::mapreduce::MapJob_MapKV* MapJob::mutable_map_kvs(int index) {
  // @@protoc_insertion_point(field_mutable:mapreduce.MapJob.map_kvs)
  return map_kvs_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::mapreduce::MapJob_MapKV >*
MapJob::mutable_map_kvs() {
  // @@protoc_insertion_point(field_mutable_list:mapreduce.MapJob.map_kvs)
  return &map_kvs_;
}
inline const ::mapreduce::MapJob_MapKV& MapJob::map_kvs(int index) const {
  // @@protoc_insertion_point(field_get:mapreduce.MapJob.map_kvs)
  return map_kvs_.Get(index);
}
inline ::mapreduce::MapJob_MapKV* MapJob::add_map_kvs() {
  // @@protoc_insertion_point(field_add:mapreduce.MapJob.map_kvs)
  return map_kvs_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::mapreduce::MapJob_MapKV >&
MapJob::map_kvs() const {
  // @@protoc_insertion_point(field_list:mapreduce.MapJob.map_kvs)
  return map_kvs_;
}

// -------------------------------------------------------------------

// ReduceJob_ReduceKV

// string key = 1;
inline void ReduceJob_ReduceKV::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ReduceJob_ReduceKV::key() const {
  // @@protoc_insertion_point(field_get:mapreduce.ReduceJob.ReduceKV.key)
  return key_.GetNoArena();
}
inline void ReduceJob_ReduceKV::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mapreduce.ReduceJob.ReduceKV.key)
}
#if LANG_CXX11
inline void ReduceJob_ReduceKV::set_key(::std::string&& value) {
  
  key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mapreduce.ReduceJob.ReduceKV.key)
}
#endif
inline void ReduceJob_ReduceKV::set_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mapreduce.ReduceJob.ReduceKV.key)
}
inline void ReduceJob_ReduceKV::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mapreduce.ReduceJob.ReduceKV.key)
}
inline ::std::string* ReduceJob_ReduceKV::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:mapreduce.ReduceJob.ReduceKV.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ReduceJob_ReduceKV::release_key() {
  // @@protoc_insertion_point(field_release:mapreduce.ReduceJob.ReduceKV.key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReduceJob_ReduceKV::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:mapreduce.ReduceJob.ReduceKV.key)
}

// repeated string value = 2;
inline int ReduceJob_ReduceKV::value_size() const {
  return value_.size();
}
inline void ReduceJob_ReduceKV::clear_value() {
  value_.Clear();
}
inline const ::std::string& ReduceJob_ReduceKV::value(int index) const {
  // @@protoc_insertion_point(field_get:mapreduce.ReduceJob.ReduceKV.value)
  return value_.Get(index);
}
inline ::std::string* ReduceJob_ReduceKV::mutable_value(int index) {
  // @@protoc_insertion_point(field_mutable:mapreduce.ReduceJob.ReduceKV.value)
  return value_.Mutable(index);
}
inline void ReduceJob_ReduceKV::set_value(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:mapreduce.ReduceJob.ReduceKV.value)
  value_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void ReduceJob_ReduceKV::set_value(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:mapreduce.ReduceJob.ReduceKV.value)
  value_.Mutable(index)->assign(std::move(value));
}
#endif
inline void ReduceJob_ReduceKV::set_value(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  value_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:mapreduce.ReduceJob.ReduceKV.value)
}
inline void ReduceJob_ReduceKV::set_value(int index, const char* value, size_t size) {
  value_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:mapreduce.ReduceJob.ReduceKV.value)
}
inline ::std::string* ReduceJob_ReduceKV::add_value() {
  // @@protoc_insertion_point(field_add_mutable:mapreduce.ReduceJob.ReduceKV.value)
  return value_.Add();
}
inline void ReduceJob_ReduceKV::add_value(const ::std::string& value) {
  value_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:mapreduce.ReduceJob.ReduceKV.value)
}
#if LANG_CXX11
inline void ReduceJob_ReduceKV::add_value(::std::string&& value) {
  value_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:mapreduce.ReduceJob.ReduceKV.value)
}
#endif
inline void ReduceJob_ReduceKV::add_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  value_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:mapreduce.ReduceJob.ReduceKV.value)
}
inline void ReduceJob_ReduceKV::add_value(const char* value, size_t size) {
  value_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:mapreduce.ReduceJob.ReduceKV.value)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
ReduceJob_ReduceKV::value() const {
  // @@protoc_insertion_point(field_list:mapreduce.ReduceJob.ReduceKV.value)
  return value_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
ReduceJob_ReduceKV::mutable_value() {
  // @@protoc_insertion_point(field_mutable_list:mapreduce.ReduceJob.ReduceKV.value)
  return &value_;
}

// -------------------------------------------------------------------

// ReduceJob

// uint32 job_id = 1;
inline void ReduceJob::clear_job_id() {
  job_id_ = 0u;
}
inline ::google::protobuf::uint32 ReduceJob::job_id() const {
  // @@protoc_insertion_point(field_get:mapreduce.ReduceJob.job_id)
  return job_id_;
}
inline void ReduceJob::set_job_id(::google::protobuf::uint32 value) {
  
  job_id_ = value;
  // @@protoc_insertion_point(field_set:mapreduce.ReduceJob.job_id)
}

// uint32 sub_job_id = 2;
inline void ReduceJob::clear_sub_job_id() {
  sub_job_id_ = 0u;
}
inline ::google::protobuf::uint32 ReduceJob::sub_job_id() const {
  // @@protoc_insertion_point(field_get:mapreduce.ReduceJob.sub_job_id)
  return sub_job_id_;
}
inline void ReduceJob::set_sub_job_id(::google::protobuf::uint32 value) {
  
  sub_job_id_ = value;
  // @@protoc_insertion_point(field_set:mapreduce.ReduceJob.sub_job_id)
}

// string name = 3;
inline void ReduceJob::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ReduceJob::name() const {
  // @@protoc_insertion_point(field_get:mapreduce.ReduceJob.name)
  return name_.GetNoArena();
}
inline void ReduceJob::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mapreduce.ReduceJob.name)
}
#if LANG_CXX11
inline void ReduceJob::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mapreduce.ReduceJob.name)
}
#endif
inline void ReduceJob::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mapreduce.ReduceJob.name)
}
inline void ReduceJob::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mapreduce.ReduceJob.name)
}
inline ::std::string* ReduceJob::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:mapreduce.ReduceJob.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ReduceJob::release_name() {
  // @@protoc_insertion_point(field_release:mapreduce.ReduceJob.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReduceJob::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:mapreduce.ReduceJob.name)
}

// string type = 4;
inline void ReduceJob::clear_type() {
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ReduceJob::type() const {
  // @@protoc_insertion_point(field_get:mapreduce.ReduceJob.type)
  return type_.GetNoArena();
}
inline void ReduceJob::set_type(const ::std::string& value) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mapreduce.ReduceJob.type)
}
#if LANG_CXX11
inline void ReduceJob::set_type(::std::string&& value) {
  
  type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mapreduce.ReduceJob.type)
}
#endif
inline void ReduceJob::set_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mapreduce.ReduceJob.type)
}
inline void ReduceJob::set_type(const char* value, size_t size) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mapreduce.ReduceJob.type)
}
inline ::std::string* ReduceJob::mutable_type() {
  
  // @@protoc_insertion_point(field_mutable:mapreduce.ReduceJob.type)
  return type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ReduceJob::release_type() {
  // @@protoc_insertion_point(field_release:mapreduce.ReduceJob.type)
  
  return type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReduceJob::set_allocated_type(::std::string* type) {
  if (type != NULL) {
    
  } else {
    
  }
  type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:mapreduce.ReduceJob.type)
}

// repeated .mapreduce.ReduceJob.ReduceKV reduce_kvs = 5;
inline int ReduceJob::reduce_kvs_size() const {
  return reduce_kvs_.size();
}
inline void ReduceJob::clear_reduce_kvs() {
  reduce_kvs_.Clear();
}
inline ::mapreduce::ReduceJob_ReduceKV* ReduceJob::mutable_reduce_kvs(int index) {
  // @@protoc_insertion_point(field_mutable:mapreduce.ReduceJob.reduce_kvs)
  return reduce_kvs_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::mapreduce::ReduceJob_ReduceKV >*
ReduceJob::mutable_reduce_kvs() {
  // @@protoc_insertion_point(field_mutable_list:mapreduce.ReduceJob.reduce_kvs)
  return &reduce_kvs_;
}
inline const ::mapreduce::ReduceJob_ReduceKV& ReduceJob::reduce_kvs(int index) const {
  // @@protoc_insertion_point(field_get:mapreduce.ReduceJob.reduce_kvs)
  return reduce_kvs_.Get(index);
}
inline ::mapreduce::ReduceJob_ReduceKV* ReduceJob::add_reduce_kvs() {
  // @@protoc_insertion_point(field_add:mapreduce.ReduceJob.reduce_kvs)
  return reduce_kvs_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::mapreduce::ReduceJob_ReduceKV >&
ReduceJob::reduce_kvs() const {
  // @@protoc_insertion_point(field_list:mapreduce.ReduceJob.reduce_kvs)
  return reduce_kvs_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mapreduce

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::mapreduce::WorkerReplyMsg_WorkerState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::mapreduce::WorkerReplyMsg_WorkerState>() {
  return ::mapreduce::WorkerReplyMsg_WorkerState_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_worker_5fservice_2eproto
