// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker_service.proto

#include "worker_service.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_worker_5fservice_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_worker_5fservice_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_MapJobMsg_MapKV;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_worker_5fservice_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ReduceJobMsg_ReduceKV;
}  // namespace protobuf_worker_5fservice_2eproto
namespace mapreduce {
class WorkerReplyMsgDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<WorkerReplyMsg>
      _instance;
} _WorkerReplyMsg_default_instance_;
class MapJobMsg_MapKVDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MapJobMsg_MapKV>
      _instance;
} _MapJobMsg_MapKV_default_instance_;
class MapJobMsgDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MapJobMsg>
      _instance;
} _MapJobMsg_default_instance_;
class ReduceJobMsg_ReduceKVDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReduceJobMsg_ReduceKV>
      _instance;
} _ReduceJobMsg_ReduceKV_default_instance_;
class ReduceJobMsgDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReduceJobMsg>
      _instance;
} _ReduceJobMsg_default_instance_;
}  // namespace mapreduce
namespace protobuf_worker_5fservice_2eproto {
static void InitDefaultsWorkerReplyMsg() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mapreduce::_WorkerReplyMsg_default_instance_;
    new (ptr) ::mapreduce::WorkerReplyMsg();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mapreduce::WorkerReplyMsg::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_WorkerReplyMsg =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsWorkerReplyMsg}, {}};

static void InitDefaultsMapJobMsg_MapKV() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mapreduce::_MapJobMsg_MapKV_default_instance_;
    new (ptr) ::mapreduce::MapJobMsg_MapKV();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mapreduce::MapJobMsg_MapKV::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_MapJobMsg_MapKV =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsMapJobMsg_MapKV}, {}};

static void InitDefaultsMapJobMsg() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mapreduce::_MapJobMsg_default_instance_;
    new (ptr) ::mapreduce::MapJobMsg();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mapreduce::MapJobMsg::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_MapJobMsg =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsMapJobMsg}, {
      &protobuf_worker_5fservice_2eproto::scc_info_MapJobMsg_MapKV.base,}};

static void InitDefaultsReduceJobMsg_ReduceKV() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mapreduce::_ReduceJobMsg_ReduceKV_default_instance_;
    new (ptr) ::mapreduce::ReduceJobMsg_ReduceKV();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mapreduce::ReduceJobMsg_ReduceKV::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ReduceJobMsg_ReduceKV =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReduceJobMsg_ReduceKV}, {}};

static void InitDefaultsReduceJobMsg() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mapreduce::_ReduceJobMsg_default_instance_;
    new (ptr) ::mapreduce::ReduceJobMsg();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mapreduce::ReduceJobMsg::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ReduceJobMsg =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsReduceJobMsg}, {
      &protobuf_worker_5fservice_2eproto::scc_info_ReduceJobMsg_ReduceKV.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_WorkerReplyMsg.base);
  ::google::protobuf::internal::InitSCC(&scc_info_MapJobMsg_MapKV.base);
  ::google::protobuf::internal::InitSCC(&scc_info_MapJobMsg.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ReduceJobMsg_ReduceKV.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ReduceJobMsg.base);
}

::google::protobuf::Metadata file_level_metadata[5];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];
const ::google::protobuf::ServiceDescriptor* file_level_service_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mapreduce::WorkerReplyMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mapreduce::WorkerReplyMsg, ok_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mapreduce::WorkerReplyMsg, msg_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mapreduce::WorkerReplyMsg, state_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mapreduce::MapJobMsg_MapKV, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mapreduce::MapJobMsg_MapKV, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mapreduce::MapJobMsg_MapKV, value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mapreduce::MapJobMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mapreduce::MapJobMsg, job_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mapreduce::MapJobMsg, sub_job_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mapreduce::MapJobMsg, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mapreduce::MapJobMsg, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mapreduce::MapJobMsg, map_kvs_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mapreduce::ReduceJobMsg_ReduceKV, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mapreduce::ReduceJobMsg_ReduceKV, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mapreduce::ReduceJobMsg_ReduceKV, value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mapreduce::ReduceJobMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mapreduce::ReduceJobMsg, job_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mapreduce::ReduceJobMsg, sub_job_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mapreduce::ReduceJobMsg, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mapreduce::ReduceJobMsg, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mapreduce::ReduceJobMsg, reduce_kvs_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::mapreduce::WorkerReplyMsg)},
  { 8, -1, sizeof(::mapreduce::MapJobMsg_MapKV)},
  { 15, -1, sizeof(::mapreduce::MapJobMsg)},
  { 25, -1, sizeof(::mapreduce::ReduceJobMsg_ReduceKV)},
  { 32, -1, sizeof(::mapreduce::ReduceJobMsg)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::mapreduce::_WorkerReplyMsg_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::mapreduce::_MapJobMsg_MapKV_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::mapreduce::_MapJobMsg_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::mapreduce::_ReduceJobMsg_ReduceKV_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::mapreduce::_ReduceJobMsg_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "worker_service.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, file_level_service_descriptors);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\024worker_service.proto\022\tmapreduce\032\033googl"
      "e/protobuf/empty.proto\"\247\001\n\016WorkerReplyMs"
      "g\022\n\n\002ok\030\001 \001(\010\022\013\n\003msg\030\002 \001(\t\0224\n\005state\030\003 \001("
      "\0162%.mapreduce.WorkerReplyMsg.WorkerState"
      "\"F\n\013WorkerState\022\013\n\007UNKNOWN\020\000\022\010\n\004INIT\020\001\022\010"
      "\n\004IDLE\020\002\022\013\n\007WORKING\020\003\022\t\n\005CLOSE\020\004\"\235\001\n\tMap"
      "JobMsg\022\016\n\006job_id\030\001 \001(\r\022\022\n\nsub_job_id\030\002 \001"
      "(\r\022\014\n\004name\030\003 \001(\t\022\014\n\004type\030\004 \001(\t\022+\n\007map_kv"
      "s\030\005 \003(\0132\032.mapreduce.MapJobMsg.MapKV\032#\n\005M"
      "apKV\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"\254\001\n\014Red"
      "uceJobMsg\022\016\n\006job_id\030\001 \001(\r\022\022\n\nsub_job_id\030"
      "\002 \001(\r\022\014\n\004name\030\003 \001(\t\022\014\n\004type\030\004 \001(\t\0224\n\nred"
      "uce_kvs\030\005 \003(\0132 .mapreduce.ReduceJobMsg.R"
      "educeKV\032&\n\010ReduceKV\022\013\n\003key\030\001 \001(\t\022\r\n\005valu"
      "e\030\002 \003(\t2\306\001\n\rWorkerService\022;\n\004Beat\022\026.goog"
      "le.protobuf.Empty\032\031.mapreduce.WorkerRepl"
      "yMsg\"\000\0228\n\003Map\022\024.mapreduce.MapJobMsg\032\031.ma"
      "preduce.WorkerReplyMsg\"\000\022>\n\006Reduce\022\027.map"
      "reduce.ReduceJobMsg\032\031.mapreduce.WorkerRe"
      "plyMsg\"\000B\003\200\001\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 781);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "worker_service.proto", &protobuf_RegisterTypes);
  ::protobuf_google_2fprotobuf_2fempty_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_worker_5fservice_2eproto
namespace mapreduce {
const ::google::protobuf::EnumDescriptor* WorkerReplyMsg_WorkerState_descriptor() {
  protobuf_worker_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_worker_5fservice_2eproto::file_level_enum_descriptors[0];
}
bool WorkerReplyMsg_WorkerState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const WorkerReplyMsg_WorkerState WorkerReplyMsg::UNKNOWN;
const WorkerReplyMsg_WorkerState WorkerReplyMsg::INIT;
const WorkerReplyMsg_WorkerState WorkerReplyMsg::IDLE;
const WorkerReplyMsg_WorkerState WorkerReplyMsg::WORKING;
const WorkerReplyMsg_WorkerState WorkerReplyMsg::CLOSE;
const WorkerReplyMsg_WorkerState WorkerReplyMsg::WorkerState_MIN;
const WorkerReplyMsg_WorkerState WorkerReplyMsg::WorkerState_MAX;
const int WorkerReplyMsg::WorkerState_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void WorkerReplyMsg::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int WorkerReplyMsg::kOkFieldNumber;
const int WorkerReplyMsg::kMsgFieldNumber;
const int WorkerReplyMsg::kStateFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

WorkerReplyMsg::WorkerReplyMsg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_worker_5fservice_2eproto::scc_info_WorkerReplyMsg.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:mapreduce.WorkerReplyMsg)
}
WorkerReplyMsg::WorkerReplyMsg(const WorkerReplyMsg& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.msg().size() > 0) {
    msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msg_);
  }
  ::memcpy(&ok_, &from.ok_,
    static_cast<size_t>(reinterpret_cast<char*>(&state_) -
    reinterpret_cast<char*>(&ok_)) + sizeof(state_));
  // @@protoc_insertion_point(copy_constructor:mapreduce.WorkerReplyMsg)
}

void WorkerReplyMsg::SharedCtor() {
  msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&ok_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&state_) -
      reinterpret_cast<char*>(&ok_)) + sizeof(state_));
}

WorkerReplyMsg::~WorkerReplyMsg() {
  // @@protoc_insertion_point(destructor:mapreduce.WorkerReplyMsg)
  SharedDtor();
}

void WorkerReplyMsg::SharedDtor() {
  msg_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void WorkerReplyMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* WorkerReplyMsg::descriptor() {
  ::protobuf_worker_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_worker_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const WorkerReplyMsg& WorkerReplyMsg::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_worker_5fservice_2eproto::scc_info_WorkerReplyMsg.base);
  return *internal_default_instance();
}


void WorkerReplyMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:mapreduce.WorkerReplyMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&ok_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&state_) -
      reinterpret_cast<char*>(&ok_)) + sizeof(state_));
  _internal_metadata_.Clear();
}

bool WorkerReplyMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mapreduce.WorkerReplyMsg)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool ok = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &ok_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string msg = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msg()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->msg().data(), static_cast<int>(this->msg().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "mapreduce.WorkerReplyMsg.msg"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .mapreduce.WorkerReplyMsg.WorkerState state = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_state(static_cast< ::mapreduce::WorkerReplyMsg_WorkerState >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mapreduce.WorkerReplyMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mapreduce.WorkerReplyMsg)
  return false;
#undef DO_
}

void WorkerReplyMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mapreduce.WorkerReplyMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool ok = 1;
  if (this->ok() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->ok(), output);
  }

  // string msg = 2;
  if (this->msg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->msg().data(), static_cast<int>(this->msg().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mapreduce.WorkerReplyMsg.msg");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->msg(), output);
  }

  // .mapreduce.WorkerReplyMsg.WorkerState state = 3;
  if (this->state() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->state(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:mapreduce.WorkerReplyMsg)
}

::google::protobuf::uint8* WorkerReplyMsg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:mapreduce.WorkerReplyMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool ok = 1;
  if (this->ok() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->ok(), target);
  }

  // string msg = 2;
  if (this->msg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->msg().data(), static_cast<int>(this->msg().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mapreduce.WorkerReplyMsg.msg");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->msg(), target);
  }

  // .mapreduce.WorkerReplyMsg.WorkerState state = 3;
  if (this->state() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->state(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mapreduce.WorkerReplyMsg)
  return target;
}

size_t WorkerReplyMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mapreduce.WorkerReplyMsg)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string msg = 2;
  if (this->msg().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->msg());
  }

  // bool ok = 1;
  if (this->ok() != 0) {
    total_size += 1 + 1;
  }

  // .mapreduce.WorkerReplyMsg.WorkerState state = 3;
  if (this->state() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->state());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void WorkerReplyMsg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mapreduce.WorkerReplyMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const WorkerReplyMsg* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const WorkerReplyMsg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mapreduce.WorkerReplyMsg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mapreduce.WorkerReplyMsg)
    MergeFrom(*source);
  }
}

void WorkerReplyMsg::MergeFrom(const WorkerReplyMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mapreduce.WorkerReplyMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.msg().size() > 0) {

    msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msg_);
  }
  if (from.ok() != 0) {
    set_ok(from.ok());
  }
  if (from.state() != 0) {
    set_state(from.state());
  }
}

void WorkerReplyMsg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mapreduce.WorkerReplyMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WorkerReplyMsg::CopyFrom(const WorkerReplyMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mapreduce.WorkerReplyMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WorkerReplyMsg::IsInitialized() const {
  return true;
}

void WorkerReplyMsg::Swap(WorkerReplyMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void WorkerReplyMsg::InternalSwap(WorkerReplyMsg* other) {
  using std::swap;
  msg_.Swap(&other->msg_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(ok_, other->ok_);
  swap(state_, other->state_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata WorkerReplyMsg::GetMetadata() const {
  protobuf_worker_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_worker_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void MapJobMsg_MapKV::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MapJobMsg_MapKV::kKeyFieldNumber;
const int MapJobMsg_MapKV::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MapJobMsg_MapKV::MapJobMsg_MapKV()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_worker_5fservice_2eproto::scc_info_MapJobMsg_MapKV.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:mapreduce.MapJobMsg.MapKV)
}
MapJobMsg_MapKV::MapJobMsg_MapKV(const MapJobMsg_MapKV& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.key().size() > 0) {
    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.value().size() > 0) {
    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  // @@protoc_insertion_point(copy_constructor:mapreduce.MapJobMsg.MapKV)
}

void MapJobMsg_MapKV::SharedCtor() {
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

MapJobMsg_MapKV::~MapJobMsg_MapKV() {
  // @@protoc_insertion_point(destructor:mapreduce.MapJobMsg.MapKV)
  SharedDtor();
}

void MapJobMsg_MapKV::SharedDtor() {
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void MapJobMsg_MapKV::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* MapJobMsg_MapKV::descriptor() {
  ::protobuf_worker_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_worker_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MapJobMsg_MapKV& MapJobMsg_MapKV::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_worker_5fservice_2eproto::scc_info_MapJobMsg_MapKV.base);
  return *internal_default_instance();
}


void MapJobMsg_MapKV::Clear() {
// @@protoc_insertion_point(message_clear_start:mapreduce.MapJobMsg.MapKV)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool MapJobMsg_MapKV::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mapreduce.MapJobMsg.MapKV)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string key = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->key().data(), static_cast<int>(this->key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "mapreduce.MapJobMsg.MapKV.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string value = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->value().data(), static_cast<int>(this->value().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "mapreduce.MapJobMsg.MapKV.value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mapreduce.MapJobMsg.MapKV)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mapreduce.MapJobMsg.MapKV)
  return false;
#undef DO_
}

void MapJobMsg_MapKV::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mapreduce.MapJobMsg.MapKV)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mapreduce.MapJobMsg.MapKV.key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->key(), output);
  }

  // string value = 2;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), static_cast<int>(this->value().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mapreduce.MapJobMsg.MapKV.value");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->value(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:mapreduce.MapJobMsg.MapKV)
}

::google::protobuf::uint8* MapJobMsg_MapKV::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:mapreduce.MapJobMsg.MapKV)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mapreduce.MapJobMsg.MapKV.key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->key(), target);
  }

  // string value = 2;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), static_cast<int>(this->value().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mapreduce.MapJobMsg.MapKV.value");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->value(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mapreduce.MapJobMsg.MapKV)
  return target;
}

size_t MapJobMsg_MapKV::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mapreduce.MapJobMsg.MapKV)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string key = 1;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->key());
  }

  // string value = 2;
  if (this->value().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->value());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MapJobMsg_MapKV::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mapreduce.MapJobMsg.MapKV)
  GOOGLE_DCHECK_NE(&from, this);
  const MapJobMsg_MapKV* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MapJobMsg_MapKV>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mapreduce.MapJobMsg.MapKV)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mapreduce.MapJobMsg.MapKV)
    MergeFrom(*source);
  }
}

void MapJobMsg_MapKV::MergeFrom(const MapJobMsg_MapKV& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mapreduce.MapJobMsg.MapKV)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.key().size() > 0) {

    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  if (from.value().size() > 0) {

    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
}

void MapJobMsg_MapKV::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mapreduce.MapJobMsg.MapKV)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MapJobMsg_MapKV::CopyFrom(const MapJobMsg_MapKV& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mapreduce.MapJobMsg.MapKV)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MapJobMsg_MapKV::IsInitialized() const {
  return true;
}

void MapJobMsg_MapKV::Swap(MapJobMsg_MapKV* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MapJobMsg_MapKV::InternalSwap(MapJobMsg_MapKV* other) {
  using std::swap;
  key_.Swap(&other->key_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  value_.Swap(&other->value_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata MapJobMsg_MapKV::GetMetadata() const {
  protobuf_worker_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_worker_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void MapJobMsg::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MapJobMsg::kJobIdFieldNumber;
const int MapJobMsg::kSubJobIdFieldNumber;
const int MapJobMsg::kNameFieldNumber;
const int MapJobMsg::kTypeFieldNumber;
const int MapJobMsg::kMapKvsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MapJobMsg::MapJobMsg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_worker_5fservice_2eproto::scc_info_MapJobMsg.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:mapreduce.MapJobMsg)
}
MapJobMsg::MapJobMsg(const MapJobMsg& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      map_kvs_(from.map_kvs_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.type().size() > 0) {
    type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type_);
  }
  ::memcpy(&job_id_, &from.job_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&sub_job_id_) -
    reinterpret_cast<char*>(&job_id_)) + sizeof(sub_job_id_));
  // @@protoc_insertion_point(copy_constructor:mapreduce.MapJobMsg)
}

void MapJobMsg::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&job_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&sub_job_id_) -
      reinterpret_cast<char*>(&job_id_)) + sizeof(sub_job_id_));
}

MapJobMsg::~MapJobMsg() {
  // @@protoc_insertion_point(destructor:mapreduce.MapJobMsg)
  SharedDtor();
}

void MapJobMsg::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void MapJobMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* MapJobMsg::descriptor() {
  ::protobuf_worker_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_worker_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MapJobMsg& MapJobMsg::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_worker_5fservice_2eproto::scc_info_MapJobMsg.base);
  return *internal_default_instance();
}


void MapJobMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:mapreduce.MapJobMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  map_kvs_.Clear();
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&job_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&sub_job_id_) -
      reinterpret_cast<char*>(&job_id_)) + sizeof(sub_job_id_));
  _internal_metadata_.Clear();
}

bool MapJobMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mapreduce.MapJobMsg)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 job_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &job_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 sub_job_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &sub_job_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string name = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "mapreduce.MapJobMsg.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string type = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_type()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->type().data(), static_cast<int>(this->type().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "mapreduce.MapJobMsg.type"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .mapreduce.MapJobMsg.MapKV map_kvs = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_map_kvs()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mapreduce.MapJobMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mapreduce.MapJobMsg)
  return false;
#undef DO_
}

void MapJobMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mapreduce.MapJobMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 job_id = 1;
  if (this->job_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->job_id(), output);
  }

  // uint32 sub_job_id = 2;
  if (this->sub_job_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->sub_job_id(), output);
  }

  // string name = 3;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mapreduce.MapJobMsg.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->name(), output);
  }

  // string type = 4;
  if (this->type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->type().data(), static_cast<int>(this->type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mapreduce.MapJobMsg.type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->type(), output);
  }

  // repeated .mapreduce.MapJobMsg.MapKV map_kvs = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->map_kvs_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5,
      this->map_kvs(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:mapreduce.MapJobMsg)
}

::google::protobuf::uint8* MapJobMsg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:mapreduce.MapJobMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 job_id = 1;
  if (this->job_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->job_id(), target);
  }

  // uint32 sub_job_id = 2;
  if (this->sub_job_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->sub_job_id(), target);
  }

  // string name = 3;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mapreduce.MapJobMsg.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->name(), target);
  }

  // string type = 4;
  if (this->type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->type().data(), static_cast<int>(this->type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mapreduce.MapJobMsg.type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->type(), target);
  }

  // repeated .mapreduce.MapJobMsg.MapKV map_kvs = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->map_kvs_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->map_kvs(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mapreduce.MapJobMsg)
  return target;
}

size_t MapJobMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mapreduce.MapJobMsg)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .mapreduce.MapJobMsg.MapKV map_kvs = 5;
  {
    unsigned int count = static_cast<unsigned int>(this->map_kvs_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->map_kvs(static_cast<int>(i)));
    }
  }

  // string name = 3;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // string type = 4;
  if (this->type().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->type());
  }

  // uint32 job_id = 1;
  if (this->job_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->job_id());
  }

  // uint32 sub_job_id = 2;
  if (this->sub_job_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->sub_job_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MapJobMsg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mapreduce.MapJobMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const MapJobMsg* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MapJobMsg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mapreduce.MapJobMsg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mapreduce.MapJobMsg)
    MergeFrom(*source);
  }
}

void MapJobMsg::MergeFrom(const MapJobMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mapreduce.MapJobMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  map_kvs_.MergeFrom(from.map_kvs_);
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.type().size() > 0) {

    type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type_);
  }
  if (from.job_id() != 0) {
    set_job_id(from.job_id());
  }
  if (from.sub_job_id() != 0) {
    set_sub_job_id(from.sub_job_id());
  }
}

void MapJobMsg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mapreduce.MapJobMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MapJobMsg::CopyFrom(const MapJobMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mapreduce.MapJobMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MapJobMsg::IsInitialized() const {
  return true;
}

void MapJobMsg::Swap(MapJobMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MapJobMsg::InternalSwap(MapJobMsg* other) {
  using std::swap;
  CastToBase(&map_kvs_)->InternalSwap(CastToBase(&other->map_kvs_));
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  type_.Swap(&other->type_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(job_id_, other->job_id_);
  swap(sub_job_id_, other->sub_job_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata MapJobMsg::GetMetadata() const {
  protobuf_worker_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_worker_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ReduceJobMsg_ReduceKV::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReduceJobMsg_ReduceKV::kKeyFieldNumber;
const int ReduceJobMsg_ReduceKV::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReduceJobMsg_ReduceKV::ReduceJobMsg_ReduceKV()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_worker_5fservice_2eproto::scc_info_ReduceJobMsg_ReduceKV.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:mapreduce.ReduceJobMsg.ReduceKV)
}
ReduceJobMsg_ReduceKV::ReduceJobMsg_ReduceKV(const ReduceJobMsg_ReduceKV& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      value_(from.value_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.key().size() > 0) {
    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  // @@protoc_insertion_point(copy_constructor:mapreduce.ReduceJobMsg.ReduceKV)
}

void ReduceJobMsg_ReduceKV::SharedCtor() {
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ReduceJobMsg_ReduceKV::~ReduceJobMsg_ReduceKV() {
  // @@protoc_insertion_point(destructor:mapreduce.ReduceJobMsg.ReduceKV)
  SharedDtor();
}

void ReduceJobMsg_ReduceKV::SharedDtor() {
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ReduceJobMsg_ReduceKV::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReduceJobMsg_ReduceKV::descriptor() {
  ::protobuf_worker_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_worker_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReduceJobMsg_ReduceKV& ReduceJobMsg_ReduceKV::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_worker_5fservice_2eproto::scc_info_ReduceJobMsg_ReduceKV.base);
  return *internal_default_instance();
}


void ReduceJobMsg_ReduceKV::Clear() {
// @@protoc_insertion_point(message_clear_start:mapreduce.ReduceJobMsg.ReduceKV)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  value_.Clear();
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool ReduceJobMsg_ReduceKV::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mapreduce.ReduceJobMsg.ReduceKV)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string key = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->key().data(), static_cast<int>(this->key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "mapreduce.ReduceJobMsg.ReduceKV.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string value = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_value()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->value(this->value_size() - 1).data(),
            static_cast<int>(this->value(this->value_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "mapreduce.ReduceJobMsg.ReduceKV.value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mapreduce.ReduceJobMsg.ReduceKV)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mapreduce.ReduceJobMsg.ReduceKV)
  return false;
#undef DO_
}

void ReduceJobMsg_ReduceKV::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mapreduce.ReduceJobMsg.ReduceKV)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mapreduce.ReduceJobMsg.ReduceKV.key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->key(), output);
  }

  // repeated string value = 2;
  for (int i = 0, n = this->value_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value(i).data(), static_cast<int>(this->value(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mapreduce.ReduceJobMsg.ReduceKV.value");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->value(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:mapreduce.ReduceJobMsg.ReduceKV)
}

::google::protobuf::uint8* ReduceJobMsg_ReduceKV::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:mapreduce.ReduceJobMsg.ReduceKV)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mapreduce.ReduceJobMsg.ReduceKV.key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->key(), target);
  }

  // repeated string value = 2;
  for (int i = 0, n = this->value_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value(i).data(), static_cast<int>(this->value(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mapreduce.ReduceJobMsg.ReduceKV.value");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->value(i), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mapreduce.ReduceJobMsg.ReduceKV)
  return target;
}

size_t ReduceJobMsg_ReduceKV::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mapreduce.ReduceJobMsg.ReduceKV)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated string value = 2;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->value_size());
  for (int i = 0, n = this->value_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->value(i));
  }

  // string key = 1;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->key());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReduceJobMsg_ReduceKV::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mapreduce.ReduceJobMsg.ReduceKV)
  GOOGLE_DCHECK_NE(&from, this);
  const ReduceJobMsg_ReduceKV* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReduceJobMsg_ReduceKV>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mapreduce.ReduceJobMsg.ReduceKV)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mapreduce.ReduceJobMsg.ReduceKV)
    MergeFrom(*source);
  }
}

void ReduceJobMsg_ReduceKV::MergeFrom(const ReduceJobMsg_ReduceKV& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mapreduce.ReduceJobMsg.ReduceKV)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  value_.MergeFrom(from.value_);
  if (from.key().size() > 0) {

    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
}

void ReduceJobMsg_ReduceKV::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mapreduce.ReduceJobMsg.ReduceKV)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReduceJobMsg_ReduceKV::CopyFrom(const ReduceJobMsg_ReduceKV& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mapreduce.ReduceJobMsg.ReduceKV)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReduceJobMsg_ReduceKV::IsInitialized() const {
  return true;
}

void ReduceJobMsg_ReduceKV::Swap(ReduceJobMsg_ReduceKV* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReduceJobMsg_ReduceKV::InternalSwap(ReduceJobMsg_ReduceKV* other) {
  using std::swap;
  value_.InternalSwap(CastToBase(&other->value_));
  key_.Swap(&other->key_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReduceJobMsg_ReduceKV::GetMetadata() const {
  protobuf_worker_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_worker_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ReduceJobMsg::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReduceJobMsg::kJobIdFieldNumber;
const int ReduceJobMsg::kSubJobIdFieldNumber;
const int ReduceJobMsg::kNameFieldNumber;
const int ReduceJobMsg::kTypeFieldNumber;
const int ReduceJobMsg::kReduceKvsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReduceJobMsg::ReduceJobMsg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_worker_5fservice_2eproto::scc_info_ReduceJobMsg.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:mapreduce.ReduceJobMsg)
}
ReduceJobMsg::ReduceJobMsg(const ReduceJobMsg& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      reduce_kvs_(from.reduce_kvs_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.type().size() > 0) {
    type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type_);
  }
  ::memcpy(&job_id_, &from.job_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&sub_job_id_) -
    reinterpret_cast<char*>(&job_id_)) + sizeof(sub_job_id_));
  // @@protoc_insertion_point(copy_constructor:mapreduce.ReduceJobMsg)
}

void ReduceJobMsg::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&job_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&sub_job_id_) -
      reinterpret_cast<char*>(&job_id_)) + sizeof(sub_job_id_));
}

ReduceJobMsg::~ReduceJobMsg() {
  // @@protoc_insertion_point(destructor:mapreduce.ReduceJobMsg)
  SharedDtor();
}

void ReduceJobMsg::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ReduceJobMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReduceJobMsg::descriptor() {
  ::protobuf_worker_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_worker_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReduceJobMsg& ReduceJobMsg::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_worker_5fservice_2eproto::scc_info_ReduceJobMsg.base);
  return *internal_default_instance();
}


void ReduceJobMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:mapreduce.ReduceJobMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  reduce_kvs_.Clear();
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&job_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&sub_job_id_) -
      reinterpret_cast<char*>(&job_id_)) + sizeof(sub_job_id_));
  _internal_metadata_.Clear();
}

bool ReduceJobMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mapreduce.ReduceJobMsg)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 job_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &job_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 sub_job_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &sub_job_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string name = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "mapreduce.ReduceJobMsg.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string type = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_type()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->type().data(), static_cast<int>(this->type().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "mapreduce.ReduceJobMsg.type"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .mapreduce.ReduceJobMsg.ReduceKV reduce_kvs = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_reduce_kvs()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mapreduce.ReduceJobMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mapreduce.ReduceJobMsg)
  return false;
#undef DO_
}

void ReduceJobMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mapreduce.ReduceJobMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 job_id = 1;
  if (this->job_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->job_id(), output);
  }

  // uint32 sub_job_id = 2;
  if (this->sub_job_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->sub_job_id(), output);
  }

  // string name = 3;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mapreduce.ReduceJobMsg.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->name(), output);
  }

  // string type = 4;
  if (this->type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->type().data(), static_cast<int>(this->type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mapreduce.ReduceJobMsg.type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->type(), output);
  }

  // repeated .mapreduce.ReduceJobMsg.ReduceKV reduce_kvs = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->reduce_kvs_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5,
      this->reduce_kvs(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:mapreduce.ReduceJobMsg)
}

::google::protobuf::uint8* ReduceJobMsg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:mapreduce.ReduceJobMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 job_id = 1;
  if (this->job_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->job_id(), target);
  }

  // uint32 sub_job_id = 2;
  if (this->sub_job_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->sub_job_id(), target);
  }

  // string name = 3;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mapreduce.ReduceJobMsg.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->name(), target);
  }

  // string type = 4;
  if (this->type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->type().data(), static_cast<int>(this->type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mapreduce.ReduceJobMsg.type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->type(), target);
  }

  // repeated .mapreduce.ReduceJobMsg.ReduceKV reduce_kvs = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->reduce_kvs_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->reduce_kvs(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mapreduce.ReduceJobMsg)
  return target;
}

size_t ReduceJobMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mapreduce.ReduceJobMsg)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .mapreduce.ReduceJobMsg.ReduceKV reduce_kvs = 5;
  {
    unsigned int count = static_cast<unsigned int>(this->reduce_kvs_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->reduce_kvs(static_cast<int>(i)));
    }
  }

  // string name = 3;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // string type = 4;
  if (this->type().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->type());
  }

  // uint32 job_id = 1;
  if (this->job_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->job_id());
  }

  // uint32 sub_job_id = 2;
  if (this->sub_job_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->sub_job_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReduceJobMsg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mapreduce.ReduceJobMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const ReduceJobMsg* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReduceJobMsg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mapreduce.ReduceJobMsg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mapreduce.ReduceJobMsg)
    MergeFrom(*source);
  }
}

void ReduceJobMsg::MergeFrom(const ReduceJobMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mapreduce.ReduceJobMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  reduce_kvs_.MergeFrom(from.reduce_kvs_);
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.type().size() > 0) {

    type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type_);
  }
  if (from.job_id() != 0) {
    set_job_id(from.job_id());
  }
  if (from.sub_job_id() != 0) {
    set_sub_job_id(from.sub_job_id());
  }
}

void ReduceJobMsg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mapreduce.ReduceJobMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReduceJobMsg::CopyFrom(const ReduceJobMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mapreduce.ReduceJobMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReduceJobMsg::IsInitialized() const {
  return true;
}

void ReduceJobMsg::Swap(ReduceJobMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReduceJobMsg::InternalSwap(ReduceJobMsg* other) {
  using std::swap;
  CastToBase(&reduce_kvs_)->InternalSwap(CastToBase(&other->reduce_kvs_));
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  type_.Swap(&other->type_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(job_id_, other->job_id_);
  swap(sub_job_id_, other->sub_job_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReduceJobMsg::GetMetadata() const {
  protobuf_worker_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_worker_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

WorkerService::~WorkerService() {}

const ::google::protobuf::ServiceDescriptor* WorkerService::descriptor() {
  protobuf_worker_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_worker_5fservice_2eproto::file_level_service_descriptors[0];
}

const ::google::protobuf::ServiceDescriptor* WorkerService::GetDescriptor() {
  return descriptor();
}

void WorkerService::Beat(::google::protobuf::RpcController* controller,
                         const ::google::protobuf::Empty*,
                         ::mapreduce::WorkerReplyMsg*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method Beat() not implemented.");
  done->Run();
}

void WorkerService::Map(::google::protobuf::RpcController* controller,
                         const ::mapreduce::MapJobMsg*,
                         ::mapreduce::WorkerReplyMsg*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method Map() not implemented.");
  done->Run();
}

void WorkerService::Reduce(::google::protobuf::RpcController* controller,
                         const ::mapreduce::ReduceJobMsg*,
                         ::mapreduce::WorkerReplyMsg*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method Reduce() not implemented.");
  done->Run();
}

void WorkerService::CallMethod(const ::google::protobuf::MethodDescriptor* method,
                             ::google::protobuf::RpcController* controller,
                             const ::google::protobuf::Message* request,
                             ::google::protobuf::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), protobuf_worker_5fservice_2eproto::file_level_service_descriptors[0]);
  switch(method->index()) {
    case 0:
      Beat(controller,
             ::google::protobuf::down_cast<const ::google::protobuf::Empty*>(request),
             ::google::protobuf::down_cast< ::mapreduce::WorkerReplyMsg*>(response),
             done);
      break;
    case 1:
      Map(controller,
             ::google::protobuf::down_cast<const ::mapreduce::MapJobMsg*>(request),
             ::google::protobuf::down_cast< ::mapreduce::WorkerReplyMsg*>(response),
             done);
      break;
    case 2:
      Reduce(controller,
             ::google::protobuf::down_cast<const ::mapreduce::ReduceJobMsg*>(request),
             ::google::protobuf::down_cast< ::mapreduce::WorkerReplyMsg*>(response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& WorkerService::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::google::protobuf::Empty::default_instance();
    case 1:
      return ::mapreduce::MapJobMsg::default_instance();
    case 2:
      return ::mapreduce::ReduceJobMsg::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
          ->GetPrototype(method->input_type());
  }
}

const ::google::protobuf::Message& WorkerService::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::mapreduce::WorkerReplyMsg::default_instance();
    case 1:
      return ::mapreduce::WorkerReplyMsg::default_instance();
    case 2:
      return ::mapreduce::WorkerReplyMsg::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
          ->GetPrototype(method->output_type());
  }
}

WorkerService_Stub::WorkerService_Stub(::google::protobuf::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
WorkerService_Stub::WorkerService_Stub(
    ::google::protobuf::RpcChannel* channel,
    ::google::protobuf::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::google::protobuf::Service::STUB_OWNS_CHANNEL) {}
WorkerService_Stub::~WorkerService_Stub() {
  if (owns_channel_) delete channel_;
}

void WorkerService_Stub::Beat(::google::protobuf::RpcController* controller,
                              const ::google::protobuf::Empty* request,
                              ::mapreduce::WorkerReplyMsg* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}
void WorkerService_Stub::Map(::google::protobuf::RpcController* controller,
                              const ::mapreduce::MapJobMsg* request,
                              ::mapreduce::WorkerReplyMsg* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(1),
                       controller, request, response, done);
}
void WorkerService_Stub::Reduce(::google::protobuf::RpcController* controller,
                              const ::mapreduce::ReduceJobMsg* request,
                              ::mapreduce::WorkerReplyMsg* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(2),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace mapreduce
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::mapreduce::WorkerReplyMsg* Arena::CreateMaybeMessage< ::mapreduce::WorkerReplyMsg >(Arena* arena) {
  return Arena::CreateInternal< ::mapreduce::WorkerReplyMsg >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::mapreduce::MapJobMsg_MapKV* Arena::CreateMaybeMessage< ::mapreduce::MapJobMsg_MapKV >(Arena* arena) {
  return Arena::CreateInternal< ::mapreduce::MapJobMsg_MapKV >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::mapreduce::MapJobMsg* Arena::CreateMaybeMessage< ::mapreduce::MapJobMsg >(Arena* arena) {
  return Arena::CreateInternal< ::mapreduce::MapJobMsg >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::mapreduce::ReduceJobMsg_ReduceKV* Arena::CreateMaybeMessage< ::mapreduce::ReduceJobMsg_ReduceKV >(Arena* arena) {
  return Arena::CreateInternal< ::mapreduce::ReduceJobMsg_ReduceKV >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::mapreduce::ReduceJobMsg* Arena::CreateMaybeMessage< ::mapreduce::ReduceJobMsg >(Arena* arena) {
  return Arena::CreateInternal< ::mapreduce::ReduceJobMsg >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
