apiVersion: v1
kind: Service
metadata: 
  name: tmrgateway-svc
spec:
  type: NodePort
  selector:
    app: tmrgateway
  ports:
  - port: tmrgateway-port
    protocol: TCP
    nodePort: 2335
    port: 2335
    targetPort: 2335