// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker_service.proto

#include "worker_service.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_worker_5fservice_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_MapJobMsg_MapKV_worker_5fservice_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_worker_5fservice_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ReduceJobMsg_ReduceKV_worker_5fservice_2eproto;
namespace tmapreduce {
class WorkerReplyMsgDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<WorkerReplyMsg> _instance;
} _WorkerReplyMsg_default_instance_;
class PrepareMsgDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PrepareMsg> _instance;
} _PrepareMsg_default_instance_;
class MapJobMsg_MapKVDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MapJobMsg_MapKV> _instance;
} _MapJobMsg_MapKV_default_instance_;
class MapJobMsgDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MapJobMsg> _instance;
} _MapJobMsg_default_instance_;
class ReduceJobMsg_ReduceKVDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ReduceJobMsg_ReduceKV> _instance;
} _ReduceJobMsg_ReduceKV_default_instance_;
class ReduceJobMsgDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ReduceJobMsg> _instance;
} _ReduceJobMsg_default_instance_;
}  // namespace tmapreduce
static void InitDefaultsscc_info_MapJobMsg_worker_5fservice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tmapreduce::_MapJobMsg_default_instance_;
    new (ptr) ::tmapreduce::MapJobMsg();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tmapreduce::MapJobMsg::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_MapJobMsg_worker_5fservice_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_MapJobMsg_worker_5fservice_2eproto}, {
      &scc_info_MapJobMsg_MapKV_worker_5fservice_2eproto.base,}};

static void InitDefaultsscc_info_MapJobMsg_MapKV_worker_5fservice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tmapreduce::_MapJobMsg_MapKV_default_instance_;
    new (ptr) ::tmapreduce::MapJobMsg_MapKV();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tmapreduce::MapJobMsg_MapKV::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_MapJobMsg_MapKV_worker_5fservice_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_MapJobMsg_MapKV_worker_5fservice_2eproto}, {}};

static void InitDefaultsscc_info_PrepareMsg_worker_5fservice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tmapreduce::_PrepareMsg_default_instance_;
    new (ptr) ::tmapreduce::PrepareMsg();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tmapreduce::PrepareMsg::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_PrepareMsg_worker_5fservice_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_PrepareMsg_worker_5fservice_2eproto}, {}};

static void InitDefaultsscc_info_ReduceJobMsg_worker_5fservice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tmapreduce::_ReduceJobMsg_default_instance_;
    new (ptr) ::tmapreduce::ReduceJobMsg();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tmapreduce::ReduceJobMsg::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ReduceJobMsg_worker_5fservice_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_ReduceJobMsg_worker_5fservice_2eproto}, {
      &scc_info_ReduceJobMsg_ReduceKV_worker_5fservice_2eproto.base,}};

static void InitDefaultsscc_info_ReduceJobMsg_ReduceKV_worker_5fservice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tmapreduce::_ReduceJobMsg_ReduceKV_default_instance_;
    new (ptr) ::tmapreduce::ReduceJobMsg_ReduceKV();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tmapreduce::ReduceJobMsg_ReduceKV::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ReduceJobMsg_ReduceKV_worker_5fservice_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ReduceJobMsg_ReduceKV_worker_5fservice_2eproto}, {}};

static void InitDefaultsscc_info_WorkerReplyMsg_worker_5fservice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tmapreduce::_WorkerReplyMsg_default_instance_;
    new (ptr) ::tmapreduce::WorkerReplyMsg();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tmapreduce::WorkerReplyMsg::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_WorkerReplyMsg_worker_5fservice_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_WorkerReplyMsg_worker_5fservice_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_worker_5fservice_2eproto[6];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_worker_5fservice_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* file_level_service_descriptors_worker_5fservice_2eproto[1];

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_worker_5fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tmapreduce::WorkerReplyMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::tmapreduce::WorkerReplyMsg, ok_),
  PROTOBUF_FIELD_OFFSET(::tmapreduce::WorkerReplyMsg, msg_),
  PROTOBUF_FIELD_OFFSET(::tmapreduce::WorkerReplyMsg, state_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tmapreduce::PrepareMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::tmapreduce::PrepareMsg, master_id_),
  PROTOBUF_FIELD_OFFSET(::tmapreduce::PrepareMsg, master_group_),
  PROTOBUF_FIELD_OFFSET(::tmapreduce::PrepareMsg, master_conf_),
  PROTOBUF_FIELD_OFFSET(::tmapreduce::PrepareMsg, job_type_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tmapreduce::MapJobMsg_MapKV, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::tmapreduce::MapJobMsg_MapKV, key_),
  PROTOBUF_FIELD_OFFSET(::tmapreduce::MapJobMsg_MapKV, value_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tmapreduce::MapJobMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::tmapreduce::MapJobMsg, master_id_),
  PROTOBUF_FIELD_OFFSET(::tmapreduce::MapJobMsg, job_id_),
  PROTOBUF_FIELD_OFFSET(::tmapreduce::MapJobMsg, subjob_id_),
  PROTOBUF_FIELD_OFFSET(::tmapreduce::MapJobMsg, name_),
  PROTOBUF_FIELD_OFFSET(::tmapreduce::MapJobMsg, type_),
  PROTOBUF_FIELD_OFFSET(::tmapreduce::MapJobMsg, map_kvs_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tmapreduce::ReduceJobMsg_ReduceKV, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::tmapreduce::ReduceJobMsg_ReduceKV, key_),
  PROTOBUF_FIELD_OFFSET(::tmapreduce::ReduceJobMsg_ReduceKV, value_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tmapreduce::ReduceJobMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::tmapreduce::ReduceJobMsg, master_id_),
  PROTOBUF_FIELD_OFFSET(::tmapreduce::ReduceJobMsg, job_id_),
  PROTOBUF_FIELD_OFFSET(::tmapreduce::ReduceJobMsg, subjob_id_),
  PROTOBUF_FIELD_OFFSET(::tmapreduce::ReduceJobMsg, name_),
  PROTOBUF_FIELD_OFFSET(::tmapreduce::ReduceJobMsg, type_),
  PROTOBUF_FIELD_OFFSET(::tmapreduce::ReduceJobMsg, reduce_kvs_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::tmapreduce::WorkerReplyMsg)},
  { 8, -1, sizeof(::tmapreduce::PrepareMsg)},
  { 17, -1, sizeof(::tmapreduce::MapJobMsg_MapKV)},
  { 24, -1, sizeof(::tmapreduce::MapJobMsg)},
  { 35, -1, sizeof(::tmapreduce::ReduceJobMsg_ReduceKV)},
  { 42, -1, sizeof(::tmapreduce::ReduceJobMsg)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::tmapreduce::_WorkerReplyMsg_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::tmapreduce::_PrepareMsg_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::tmapreduce::_MapJobMsg_MapKV_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::tmapreduce::_MapJobMsg_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::tmapreduce::_ReduceJobMsg_ReduceKV_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::tmapreduce::_ReduceJobMsg_default_instance_),
};

const char descriptor_table_protodef_worker_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024worker_service.proto\022\ntmapreduce\032\033goog"
  "le/protobuf/empty.proto\032\013state.proto\"Q\n\016"
  "WorkerReplyMsg\022\n\n\002ok\030\001 \001(\010\022\013\n\003msg\030\002 \001(\t\022"
  "&\n\005state\030\003 \001(\0162\027.tmapreduce.WorkerState\""
  "\\\n\nPrepareMsg\022\021\n\tmaster_id\030\001 \001(\r\022\024\n\014mast"
  "er_group\030\002 \001(\t\022\023\n\013master_conf\030\003 \001(\t\022\020\n\010j"
  "ob_type\030\004 \001(\t\"\260\001\n\tMapJobMsg\022\021\n\tmaster_id"
  "\030\001 \001(\r\022\016\n\006job_id\030\002 \001(\r\022\021\n\tsubjob_id\030\003 \001("
  "\r\022\014\n\004name\030\004 \001(\t\022\014\n\004type\030\005 \001(\t\022,\n\007map_kvs"
  "\030\006 \003(\0132\033.tmapreduce.MapJobMsg.MapKV\032#\n\005M"
  "apKV\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"\277\001\n\014Red"
  "uceJobMsg\022\021\n\tmaster_id\030\001 \001(\r\022\016\n\006job_id\030\002"
  " \001(\r\022\021\n\tsubjob_id\030\003 \001(\r\022\014\n\004name\030\004 \001(\t\022\014\n"
  "\004type\030\005 \001(\t\0225\n\nreduce_kvs\030\006 \003(\0132!.tmapre"
  "duce.ReduceJobMsg.ReduceKV\032&\n\010ReduceKV\022\013"
  "\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \003(\t2\331\002\n\rWorkerSer"
  "vice\022<\n\004Beat\022\026.google.protobuf.Empty\032\032.t"
  "mapreduce.WorkerReplyMsg\"\000\022\?\n\007Prepare\022\026."
  "tmapreduce.PrepareMsg\032\032.tmapreduce.Worke"
  "rReplyMsg\"\000\022A\n\nPrepareMap\022\025.tmapreduce.M"
  "apJobMsg\032\032.tmapreduce.WorkerReplyMsg\"\000\022G"
  "\n\rPrepareReduce\022\030.tmapreduce.ReduceJobMs"
  "g\032\032.tmapreduce.WorkerReplyMsg\"\000\022=\n\005Start"
  "\022\026.google.protobuf.Empty\032\032.tmapreduce.Wo"
  "rkerReplyMsg\"\000B\003\200\001\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_worker_5fservice_2eproto_deps[2] = {
  &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
  &::descriptor_table_state_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_worker_5fservice_2eproto_sccs[6] = {
  &scc_info_MapJobMsg_worker_5fservice_2eproto.base,
  &scc_info_MapJobMsg_MapKV_worker_5fservice_2eproto.base,
  &scc_info_PrepareMsg_worker_5fservice_2eproto.base,
  &scc_info_ReduceJobMsg_worker_5fservice_2eproto.base,
  &scc_info_ReduceJobMsg_ReduceKV_worker_5fservice_2eproto.base,
  &scc_info_WorkerReplyMsg_worker_5fservice_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_worker_5fservice_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_worker_5fservice_2eproto = {
  false, false, descriptor_table_protodef_worker_5fservice_2eproto, "worker_service.proto", 987,
  &descriptor_table_worker_5fservice_2eproto_once, descriptor_table_worker_5fservice_2eproto_sccs, descriptor_table_worker_5fservice_2eproto_deps, 6, 2,
  schemas, file_default_instances, TableStruct_worker_5fservice_2eproto::offsets,
  file_level_metadata_worker_5fservice_2eproto, 6, file_level_enum_descriptors_worker_5fservice_2eproto, file_level_service_descriptors_worker_5fservice_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_worker_5fservice_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_worker_5fservice_2eproto)), true);
namespace tmapreduce {

// ===================================================================

void WorkerReplyMsg::InitAsDefaultInstance() {
}
class WorkerReplyMsg::_Internal {
 public:
};

WorkerReplyMsg::WorkerReplyMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tmapreduce.WorkerReplyMsg)
}
WorkerReplyMsg::WorkerReplyMsg(const WorkerReplyMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  msg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_msg().empty()) {
    msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_msg(),
      GetArena());
  }
  ::memcpy(&ok_, &from.ok_,
    static_cast<size_t>(reinterpret_cast<char*>(&state_) -
    reinterpret_cast<char*>(&ok_)) + sizeof(state_));
  // @@protoc_insertion_point(copy_constructor:tmapreduce.WorkerReplyMsg)
}

void WorkerReplyMsg::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_WorkerReplyMsg_worker_5fservice_2eproto.base);
  msg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&ok_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&state_) -
      reinterpret_cast<char*>(&ok_)) + sizeof(state_));
}

WorkerReplyMsg::~WorkerReplyMsg() {
  // @@protoc_insertion_point(destructor:tmapreduce.WorkerReplyMsg)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void WorkerReplyMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  msg_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void WorkerReplyMsg::ArenaDtor(void* object) {
  WorkerReplyMsg* _this = reinterpret_cast< WorkerReplyMsg* >(object);
  (void)_this;
}
void WorkerReplyMsg::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void WorkerReplyMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const WorkerReplyMsg& WorkerReplyMsg::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_WorkerReplyMsg_worker_5fservice_2eproto.base);
  return *internal_default_instance();
}


void WorkerReplyMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:tmapreduce.WorkerReplyMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  msg_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&ok_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&state_) -
      reinterpret_cast<char*>(&ok_)) + sizeof(state_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* WorkerReplyMsg::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bool ok = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ok_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string msg = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_msg();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "tmapreduce.WorkerReplyMsg.msg"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .tmapreduce.WorkerState state = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_state(static_cast<::tmapreduce::WorkerState>(val));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* WorkerReplyMsg::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tmapreduce.WorkerReplyMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool ok = 1;
  if (this->ok() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_ok(), target);
  }

  // string msg = 2;
  if (this->msg().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_msg().data(), static_cast<int>(this->_internal_msg().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "tmapreduce.WorkerReplyMsg.msg");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_msg(), target);
  }

  // .tmapreduce.WorkerState state = 3;
  if (this->state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      3, this->_internal_state(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tmapreduce.WorkerReplyMsg)
  return target;
}

size_t WorkerReplyMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tmapreduce.WorkerReplyMsg)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string msg = 2;
  if (this->msg().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_msg());
  }

  // bool ok = 1;
  if (this->ok() != 0) {
    total_size += 1 + 1;
  }

  // .tmapreduce.WorkerState state = 3;
  if (this->state() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_state());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void WorkerReplyMsg::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tmapreduce.WorkerReplyMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const WorkerReplyMsg* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<WorkerReplyMsg>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tmapreduce.WorkerReplyMsg)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tmapreduce.WorkerReplyMsg)
    MergeFrom(*source);
  }
}

void WorkerReplyMsg::MergeFrom(const WorkerReplyMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tmapreduce.WorkerReplyMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.msg().size() > 0) {
    _internal_set_msg(from._internal_msg());
  }
  if (from.ok() != 0) {
    _internal_set_ok(from._internal_ok());
  }
  if (from.state() != 0) {
    _internal_set_state(from._internal_state());
  }
}

void WorkerReplyMsg::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tmapreduce.WorkerReplyMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WorkerReplyMsg::CopyFrom(const WorkerReplyMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tmapreduce.WorkerReplyMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WorkerReplyMsg::IsInitialized() const {
  return true;
}

void WorkerReplyMsg::InternalSwap(WorkerReplyMsg* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  msg_.Swap(&other->msg_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(WorkerReplyMsg, state_)
      + sizeof(WorkerReplyMsg::state_)
      - PROTOBUF_FIELD_OFFSET(WorkerReplyMsg, ok_)>(
          reinterpret_cast<char*>(&ok_),
          reinterpret_cast<char*>(&other->ok_));
}

::PROTOBUF_NAMESPACE_ID::Metadata WorkerReplyMsg::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void PrepareMsg::InitAsDefaultInstance() {
}
class PrepareMsg::_Internal {
 public:
};

PrepareMsg::PrepareMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tmapreduce.PrepareMsg)
}
PrepareMsg::PrepareMsg(const PrepareMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  master_group_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_master_group().empty()) {
    master_group_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_master_group(),
      GetArena());
  }
  master_conf_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_master_conf().empty()) {
    master_conf_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_master_conf(),
      GetArena());
  }
  job_type_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_job_type().empty()) {
    job_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_job_type(),
      GetArena());
  }
  master_id_ = from.master_id_;
  // @@protoc_insertion_point(copy_constructor:tmapreduce.PrepareMsg)
}

void PrepareMsg::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_PrepareMsg_worker_5fservice_2eproto.base);
  master_group_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  master_conf_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  job_type_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  master_id_ = 0u;
}

PrepareMsg::~PrepareMsg() {
  // @@protoc_insertion_point(destructor:tmapreduce.PrepareMsg)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void PrepareMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  master_group_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  master_conf_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  job_type_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void PrepareMsg::ArenaDtor(void* object) {
  PrepareMsg* _this = reinterpret_cast< PrepareMsg* >(object);
  (void)_this;
}
void PrepareMsg::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PrepareMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PrepareMsg& PrepareMsg::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PrepareMsg_worker_5fservice_2eproto.base);
  return *internal_default_instance();
}


void PrepareMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:tmapreduce.PrepareMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  master_group_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  master_conf_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  job_type_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  master_id_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PrepareMsg::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 master_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          master_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string master_group = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_master_group();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "tmapreduce.PrepareMsg.master_group"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string master_conf = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_master_conf();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "tmapreduce.PrepareMsg.master_conf"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string job_type = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_job_type();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "tmapreduce.PrepareMsg.job_type"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PrepareMsg::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tmapreduce.PrepareMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 master_id = 1;
  if (this->master_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_master_id(), target);
  }

  // string master_group = 2;
  if (this->master_group().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_master_group().data(), static_cast<int>(this->_internal_master_group().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "tmapreduce.PrepareMsg.master_group");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_master_group(), target);
  }

  // string master_conf = 3;
  if (this->master_conf().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_master_conf().data(), static_cast<int>(this->_internal_master_conf().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "tmapreduce.PrepareMsg.master_conf");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_master_conf(), target);
  }

  // string job_type = 4;
  if (this->job_type().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_job_type().data(), static_cast<int>(this->_internal_job_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "tmapreduce.PrepareMsg.job_type");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_job_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tmapreduce.PrepareMsg)
  return target;
}

size_t PrepareMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tmapreduce.PrepareMsg)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string master_group = 2;
  if (this->master_group().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_master_group());
  }

  // string master_conf = 3;
  if (this->master_conf().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_master_conf());
  }

  // string job_type = 4;
  if (this->job_type().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_job_type());
  }

  // uint32 master_id = 1;
  if (this->master_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_master_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PrepareMsg::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tmapreduce.PrepareMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const PrepareMsg* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PrepareMsg>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tmapreduce.PrepareMsg)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tmapreduce.PrepareMsg)
    MergeFrom(*source);
  }
}

void PrepareMsg::MergeFrom(const PrepareMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tmapreduce.PrepareMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.master_group().size() > 0) {
    _internal_set_master_group(from._internal_master_group());
  }
  if (from.master_conf().size() > 0) {
    _internal_set_master_conf(from._internal_master_conf());
  }
  if (from.job_type().size() > 0) {
    _internal_set_job_type(from._internal_job_type());
  }
  if (from.master_id() != 0) {
    _internal_set_master_id(from._internal_master_id());
  }
}

void PrepareMsg::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tmapreduce.PrepareMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PrepareMsg::CopyFrom(const PrepareMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tmapreduce.PrepareMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PrepareMsg::IsInitialized() const {
  return true;
}

void PrepareMsg::InternalSwap(PrepareMsg* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  master_group_.Swap(&other->master_group_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  master_conf_.Swap(&other->master_conf_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  job_type_.Swap(&other->job_type_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(master_id_, other->master_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PrepareMsg::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void MapJobMsg_MapKV::InitAsDefaultInstance() {
}
class MapJobMsg_MapKV::_Internal {
 public:
};

MapJobMsg_MapKV::MapJobMsg_MapKV(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tmapreduce.MapJobMsg.MapKV)
}
MapJobMsg_MapKV::MapJobMsg_MapKV(const MapJobMsg_MapKV& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_key().empty()) {
    key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_key(),
      GetArena());
  }
  value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_value().empty()) {
    value_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_value(),
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:tmapreduce.MapJobMsg.MapKV)
}

void MapJobMsg_MapKV::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_MapJobMsg_MapKV_worker_5fservice_2eproto.base);
  key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

MapJobMsg_MapKV::~MapJobMsg_MapKV() {
  // @@protoc_insertion_point(destructor:tmapreduce.MapJobMsg.MapKV)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void MapJobMsg_MapKV::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  key_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  value_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void MapJobMsg_MapKV::ArenaDtor(void* object) {
  MapJobMsg_MapKV* _this = reinterpret_cast< MapJobMsg_MapKV* >(object);
  (void)_this;
}
void MapJobMsg_MapKV::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void MapJobMsg_MapKV::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MapJobMsg_MapKV& MapJobMsg_MapKV::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MapJobMsg_MapKV_worker_5fservice_2eproto.base);
  return *internal_default_instance();
}


void MapJobMsg_MapKV::Clear() {
// @@protoc_insertion_point(message_clear_start:tmapreduce.MapJobMsg.MapKV)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  key_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  value_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MapJobMsg_MapKV::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string key = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_key();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "tmapreduce.MapJobMsg.MapKV.key"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string value = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_value();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "tmapreduce.MapJobMsg.MapKV.value"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MapJobMsg_MapKV::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tmapreduce.MapJobMsg.MapKV)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (this->key().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_key().data(), static_cast<int>(this->_internal_key().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "tmapreduce.MapJobMsg.MapKV.key");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_key(), target);
  }

  // string value = 2;
  if (this->value().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_value().data(), static_cast<int>(this->_internal_value().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "tmapreduce.MapJobMsg.MapKV.value");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tmapreduce.MapJobMsg.MapKV)
  return target;
}

size_t MapJobMsg_MapKV::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tmapreduce.MapJobMsg.MapKV)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string key = 1;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_key());
  }

  // string value = 2;
  if (this->value().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_value());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MapJobMsg_MapKV::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tmapreduce.MapJobMsg.MapKV)
  GOOGLE_DCHECK_NE(&from, this);
  const MapJobMsg_MapKV* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<MapJobMsg_MapKV>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tmapreduce.MapJobMsg.MapKV)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tmapreduce.MapJobMsg.MapKV)
    MergeFrom(*source);
  }
}

void MapJobMsg_MapKV::MergeFrom(const MapJobMsg_MapKV& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tmapreduce.MapJobMsg.MapKV)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.key().size() > 0) {
    _internal_set_key(from._internal_key());
  }
  if (from.value().size() > 0) {
    _internal_set_value(from._internal_value());
  }
}

void MapJobMsg_MapKV::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tmapreduce.MapJobMsg.MapKV)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MapJobMsg_MapKV::CopyFrom(const MapJobMsg_MapKV& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tmapreduce.MapJobMsg.MapKV)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MapJobMsg_MapKV::IsInitialized() const {
  return true;
}

void MapJobMsg_MapKV::InternalSwap(MapJobMsg_MapKV* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  key_.Swap(&other->key_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  value_.Swap(&other->value_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata MapJobMsg_MapKV::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void MapJobMsg::InitAsDefaultInstance() {
}
class MapJobMsg::_Internal {
 public:
};

MapJobMsg::MapJobMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  map_kvs_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tmapreduce.MapJobMsg)
}
MapJobMsg::MapJobMsg(const MapJobMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      map_kvs_(from.map_kvs_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_name(),
      GetArena());
  }
  type_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_type().empty()) {
    type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_type(),
      GetArena());
  }
  ::memcpy(&master_id_, &from.master_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&subjob_id_) -
    reinterpret_cast<char*>(&master_id_)) + sizeof(subjob_id_));
  // @@protoc_insertion_point(copy_constructor:tmapreduce.MapJobMsg)
}

void MapJobMsg::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_MapJobMsg_worker_5fservice_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  type_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&master_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&subjob_id_) -
      reinterpret_cast<char*>(&master_id_)) + sizeof(subjob_id_));
}

MapJobMsg::~MapJobMsg() {
  // @@protoc_insertion_point(destructor:tmapreduce.MapJobMsg)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void MapJobMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  type_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void MapJobMsg::ArenaDtor(void* object) {
  MapJobMsg* _this = reinterpret_cast< MapJobMsg* >(object);
  (void)_this;
}
void MapJobMsg::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void MapJobMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MapJobMsg& MapJobMsg::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MapJobMsg_worker_5fservice_2eproto.base);
  return *internal_default_instance();
}


void MapJobMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:tmapreduce.MapJobMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  map_kvs_.Clear();
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  type_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&master_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&subjob_id_) -
      reinterpret_cast<char*>(&master_id_)) + sizeof(subjob_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MapJobMsg::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 master_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          master_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 job_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          job_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 subjob_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          subjob_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string name = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "tmapreduce.MapJobMsg.name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string type = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          auto str = _internal_mutable_type();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "tmapreduce.MapJobMsg.type"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .tmapreduce.MapJobMsg.MapKV map_kvs = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_map_kvs(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MapJobMsg::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tmapreduce.MapJobMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 master_id = 1;
  if (this->master_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_master_id(), target);
  }

  // uint32 job_id = 2;
  if (this->job_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_job_id(), target);
  }

  // uint32 subjob_id = 3;
  if (this->subjob_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_subjob_id(), target);
  }

  // string name = 4;
  if (this->name().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "tmapreduce.MapJobMsg.name");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_name(), target);
  }

  // string type = 5;
  if (this->type().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_type().data(), static_cast<int>(this->_internal_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "tmapreduce.MapJobMsg.type");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_type(), target);
  }

  // repeated .tmapreduce.MapJobMsg.MapKV map_kvs = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_map_kvs_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, this->_internal_map_kvs(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tmapreduce.MapJobMsg)
  return target;
}

size_t MapJobMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tmapreduce.MapJobMsg)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .tmapreduce.MapJobMsg.MapKV map_kvs = 6;
  total_size += 1UL * this->_internal_map_kvs_size();
  for (const auto& msg : this->map_kvs_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string name = 4;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // string type = 5;
  if (this->type().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_type());
  }

  // uint32 master_id = 1;
  if (this->master_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_master_id());
  }

  // uint32 job_id = 2;
  if (this->job_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_job_id());
  }

  // uint32 subjob_id = 3;
  if (this->subjob_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_subjob_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MapJobMsg::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tmapreduce.MapJobMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const MapJobMsg* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<MapJobMsg>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tmapreduce.MapJobMsg)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tmapreduce.MapJobMsg)
    MergeFrom(*source);
  }
}

void MapJobMsg::MergeFrom(const MapJobMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tmapreduce.MapJobMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  map_kvs_.MergeFrom(from.map_kvs_);
  if (from.name().size() > 0) {
    _internal_set_name(from._internal_name());
  }
  if (from.type().size() > 0) {
    _internal_set_type(from._internal_type());
  }
  if (from.master_id() != 0) {
    _internal_set_master_id(from._internal_master_id());
  }
  if (from.job_id() != 0) {
    _internal_set_job_id(from._internal_job_id());
  }
  if (from.subjob_id() != 0) {
    _internal_set_subjob_id(from._internal_subjob_id());
  }
}

void MapJobMsg::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tmapreduce.MapJobMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MapJobMsg::CopyFrom(const MapJobMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tmapreduce.MapJobMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MapJobMsg::IsInitialized() const {
  return true;
}

void MapJobMsg::InternalSwap(MapJobMsg* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  map_kvs_.InternalSwap(&other->map_kvs_);
  name_.Swap(&other->name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  type_.Swap(&other->type_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MapJobMsg, subjob_id_)
      + sizeof(MapJobMsg::subjob_id_)
      - PROTOBUF_FIELD_OFFSET(MapJobMsg, master_id_)>(
          reinterpret_cast<char*>(&master_id_),
          reinterpret_cast<char*>(&other->master_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MapJobMsg::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ReduceJobMsg_ReduceKV::InitAsDefaultInstance() {
}
class ReduceJobMsg_ReduceKV::_Internal {
 public:
};

ReduceJobMsg_ReduceKV::ReduceJobMsg_ReduceKV(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  value_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tmapreduce.ReduceJobMsg.ReduceKV)
}
ReduceJobMsg_ReduceKV::ReduceJobMsg_ReduceKV(const ReduceJobMsg_ReduceKV& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      value_(from.value_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_key().empty()) {
    key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_key(),
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:tmapreduce.ReduceJobMsg.ReduceKV)
}

void ReduceJobMsg_ReduceKV::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ReduceJobMsg_ReduceKV_worker_5fservice_2eproto.base);
  key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

ReduceJobMsg_ReduceKV::~ReduceJobMsg_ReduceKV() {
  // @@protoc_insertion_point(destructor:tmapreduce.ReduceJobMsg.ReduceKV)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ReduceJobMsg_ReduceKV::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  key_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ReduceJobMsg_ReduceKV::ArenaDtor(void* object) {
  ReduceJobMsg_ReduceKV* _this = reinterpret_cast< ReduceJobMsg_ReduceKV* >(object);
  (void)_this;
}
void ReduceJobMsg_ReduceKV::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ReduceJobMsg_ReduceKV::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ReduceJobMsg_ReduceKV& ReduceJobMsg_ReduceKV::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ReduceJobMsg_ReduceKV_worker_5fservice_2eproto.base);
  return *internal_default_instance();
}


void ReduceJobMsg_ReduceKV::Clear() {
// @@protoc_insertion_point(message_clear_start:tmapreduce.ReduceJobMsg.ReduceKV)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  value_.Clear();
  key_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReduceJobMsg_ReduceKV::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string key = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_key();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "tmapreduce.ReduceJobMsg.ReduceKV.key"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated string value = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_value();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "tmapreduce.ReduceJobMsg.ReduceKV.value"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ReduceJobMsg_ReduceKV::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tmapreduce.ReduceJobMsg.ReduceKV)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (this->key().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_key().data(), static_cast<int>(this->_internal_key().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "tmapreduce.ReduceJobMsg.ReduceKV.key");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_key(), target);
  }

  // repeated string value = 2;
  for (int i = 0, n = this->_internal_value_size(); i < n; i++) {
    const auto& s = this->_internal_value(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "tmapreduce.ReduceJobMsg.ReduceKV.value");
    target = stream->WriteString(2, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tmapreduce.ReduceJobMsg.ReduceKV)
  return target;
}

size_t ReduceJobMsg_ReduceKV::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tmapreduce.ReduceJobMsg.ReduceKV)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string value = 2;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(value_.size());
  for (int i = 0, n = value_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      value_.Get(i));
  }

  // string key = 1;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_key());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReduceJobMsg_ReduceKV::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tmapreduce.ReduceJobMsg.ReduceKV)
  GOOGLE_DCHECK_NE(&from, this);
  const ReduceJobMsg_ReduceKV* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ReduceJobMsg_ReduceKV>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tmapreduce.ReduceJobMsg.ReduceKV)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tmapreduce.ReduceJobMsg.ReduceKV)
    MergeFrom(*source);
  }
}

void ReduceJobMsg_ReduceKV::MergeFrom(const ReduceJobMsg_ReduceKV& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tmapreduce.ReduceJobMsg.ReduceKV)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  value_.MergeFrom(from.value_);
  if (from.key().size() > 0) {
    _internal_set_key(from._internal_key());
  }
}

void ReduceJobMsg_ReduceKV::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tmapreduce.ReduceJobMsg.ReduceKV)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReduceJobMsg_ReduceKV::CopyFrom(const ReduceJobMsg_ReduceKV& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tmapreduce.ReduceJobMsg.ReduceKV)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReduceJobMsg_ReduceKV::IsInitialized() const {
  return true;
}

void ReduceJobMsg_ReduceKV::InternalSwap(ReduceJobMsg_ReduceKV* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  value_.InternalSwap(&other->value_);
  key_.Swap(&other->key_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata ReduceJobMsg_ReduceKV::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ReduceJobMsg::InitAsDefaultInstance() {
}
class ReduceJobMsg::_Internal {
 public:
};

ReduceJobMsg::ReduceJobMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  reduce_kvs_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tmapreduce.ReduceJobMsg)
}
ReduceJobMsg::ReduceJobMsg(const ReduceJobMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      reduce_kvs_(from.reduce_kvs_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_name(),
      GetArena());
  }
  type_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_type().empty()) {
    type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_type(),
      GetArena());
  }
  ::memcpy(&master_id_, &from.master_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&subjob_id_) -
    reinterpret_cast<char*>(&master_id_)) + sizeof(subjob_id_));
  // @@protoc_insertion_point(copy_constructor:tmapreduce.ReduceJobMsg)
}

void ReduceJobMsg::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ReduceJobMsg_worker_5fservice_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  type_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&master_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&subjob_id_) -
      reinterpret_cast<char*>(&master_id_)) + sizeof(subjob_id_));
}

ReduceJobMsg::~ReduceJobMsg() {
  // @@protoc_insertion_point(destructor:tmapreduce.ReduceJobMsg)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ReduceJobMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  type_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ReduceJobMsg::ArenaDtor(void* object) {
  ReduceJobMsg* _this = reinterpret_cast< ReduceJobMsg* >(object);
  (void)_this;
}
void ReduceJobMsg::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ReduceJobMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ReduceJobMsg& ReduceJobMsg::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ReduceJobMsg_worker_5fservice_2eproto.base);
  return *internal_default_instance();
}


void ReduceJobMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:tmapreduce.ReduceJobMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  reduce_kvs_.Clear();
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  type_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&master_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&subjob_id_) -
      reinterpret_cast<char*>(&master_id_)) + sizeof(subjob_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReduceJobMsg::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 master_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          master_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 job_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          job_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 subjob_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          subjob_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string name = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "tmapreduce.ReduceJobMsg.name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string type = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          auto str = _internal_mutable_type();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "tmapreduce.ReduceJobMsg.type"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .tmapreduce.ReduceJobMsg.ReduceKV reduce_kvs = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_reduce_kvs(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ReduceJobMsg::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tmapreduce.ReduceJobMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 master_id = 1;
  if (this->master_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_master_id(), target);
  }

  // uint32 job_id = 2;
  if (this->job_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_job_id(), target);
  }

  // uint32 subjob_id = 3;
  if (this->subjob_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_subjob_id(), target);
  }

  // string name = 4;
  if (this->name().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "tmapreduce.ReduceJobMsg.name");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_name(), target);
  }

  // string type = 5;
  if (this->type().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_type().data(), static_cast<int>(this->_internal_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "tmapreduce.ReduceJobMsg.type");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_type(), target);
  }

  // repeated .tmapreduce.ReduceJobMsg.ReduceKV reduce_kvs = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_reduce_kvs_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, this->_internal_reduce_kvs(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tmapreduce.ReduceJobMsg)
  return target;
}

size_t ReduceJobMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tmapreduce.ReduceJobMsg)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .tmapreduce.ReduceJobMsg.ReduceKV reduce_kvs = 6;
  total_size += 1UL * this->_internal_reduce_kvs_size();
  for (const auto& msg : this->reduce_kvs_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string name = 4;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // string type = 5;
  if (this->type().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_type());
  }

  // uint32 master_id = 1;
  if (this->master_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_master_id());
  }

  // uint32 job_id = 2;
  if (this->job_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_job_id());
  }

  // uint32 subjob_id = 3;
  if (this->subjob_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_subjob_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReduceJobMsg::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tmapreduce.ReduceJobMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const ReduceJobMsg* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ReduceJobMsg>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tmapreduce.ReduceJobMsg)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tmapreduce.ReduceJobMsg)
    MergeFrom(*source);
  }
}

void ReduceJobMsg::MergeFrom(const ReduceJobMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tmapreduce.ReduceJobMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  reduce_kvs_.MergeFrom(from.reduce_kvs_);
  if (from.name().size() > 0) {
    _internal_set_name(from._internal_name());
  }
  if (from.type().size() > 0) {
    _internal_set_type(from._internal_type());
  }
  if (from.master_id() != 0) {
    _internal_set_master_id(from._internal_master_id());
  }
  if (from.job_id() != 0) {
    _internal_set_job_id(from._internal_job_id());
  }
  if (from.subjob_id() != 0) {
    _internal_set_subjob_id(from._internal_subjob_id());
  }
}

void ReduceJobMsg::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tmapreduce.ReduceJobMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReduceJobMsg::CopyFrom(const ReduceJobMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tmapreduce.ReduceJobMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReduceJobMsg::IsInitialized() const {
  return true;
}

void ReduceJobMsg::InternalSwap(ReduceJobMsg* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  reduce_kvs_.InternalSwap(&other->reduce_kvs_);
  name_.Swap(&other->name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  type_.Swap(&other->type_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ReduceJobMsg, subjob_id_)
      + sizeof(ReduceJobMsg::subjob_id_)
      - PROTOBUF_FIELD_OFFSET(ReduceJobMsg, master_id_)>(
          reinterpret_cast<char*>(&master_id_),
          reinterpret_cast<char*>(&other->master_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ReduceJobMsg::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

WorkerService::~WorkerService() {}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* WorkerService::descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_worker_5fservice_2eproto);
  return file_level_service_descriptors_worker_5fservice_2eproto[0];
}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* WorkerService::GetDescriptor() {
  return descriptor();
}

void WorkerService::Beat(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const PROTOBUF_NAMESPACE_ID::Empty*,
                         ::tmapreduce::WorkerReplyMsg*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method Beat() not implemented.");
  done->Run();
}

void WorkerService::Prepare(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::tmapreduce::PrepareMsg*,
                         ::tmapreduce::WorkerReplyMsg*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method Prepare() not implemented.");
  done->Run();
}

void WorkerService::PrepareMap(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::tmapreduce::MapJobMsg*,
                         ::tmapreduce::WorkerReplyMsg*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method PrepareMap() not implemented.");
  done->Run();
}

void WorkerService::PrepareReduce(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::tmapreduce::ReduceJobMsg*,
                         ::tmapreduce::WorkerReplyMsg*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method PrepareReduce() not implemented.");
  done->Run();
}

void WorkerService::Start(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const PROTOBUF_NAMESPACE_ID::Empty*,
                         ::tmapreduce::WorkerReplyMsg*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method Start() not implemented.");
  done->Run();
}

void WorkerService::CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                             ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                             const ::PROTOBUF_NAMESPACE_ID::Message* request,
                             ::PROTOBUF_NAMESPACE_ID::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), file_level_service_descriptors_worker_5fservice_2eproto[0]);
  switch(method->index()) {
    case 0:
      Beat(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const PROTOBUF_NAMESPACE_ID::Empty*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::tmapreduce::WorkerReplyMsg*>(
                 response),
             done);
      break;
    case 1:
      Prepare(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::tmapreduce::PrepareMsg*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::tmapreduce::WorkerReplyMsg*>(
                 response),
             done);
      break;
    case 2:
      PrepareMap(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::tmapreduce::MapJobMsg*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::tmapreduce::WorkerReplyMsg*>(
                 response),
             done);
      break;
    case 3:
      PrepareReduce(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::tmapreduce::ReduceJobMsg*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::tmapreduce::WorkerReplyMsg*>(
                 response),
             done);
      break;
    case 4:
      Start(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const PROTOBUF_NAMESPACE_ID::Empty*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::tmapreduce::WorkerReplyMsg*>(
                 response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& WorkerService::GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return PROTOBUF_NAMESPACE_ID::Empty::default_instance();
    case 1:
      return ::tmapreduce::PrepareMsg::default_instance();
    case 2:
      return ::tmapreduce::MapJobMsg::default_instance();
    case 3:
      return ::tmapreduce::ReduceJobMsg::default_instance();
    case 4:
      return PROTOBUF_NAMESPACE_ID::Empty::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->input_type());
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& WorkerService::GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::tmapreduce::WorkerReplyMsg::default_instance();
    case 1:
      return ::tmapreduce::WorkerReplyMsg::default_instance();
    case 2:
      return ::tmapreduce::WorkerReplyMsg::default_instance();
    case 3:
      return ::tmapreduce::WorkerReplyMsg::default_instance();
    case 4:
      return ::tmapreduce::WorkerReplyMsg::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->output_type());
  }
}

WorkerService_Stub::WorkerService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
WorkerService_Stub::WorkerService_Stub(
    ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
    ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::PROTOBUF_NAMESPACE_ID::Service::STUB_OWNS_CHANNEL) {}
WorkerService_Stub::~WorkerService_Stub() {
  if (owns_channel_) delete channel_;
}

void WorkerService_Stub::Beat(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const PROTOBUF_NAMESPACE_ID::Empty* request,
                              ::tmapreduce::WorkerReplyMsg* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}
void WorkerService_Stub::Prepare(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::tmapreduce::PrepareMsg* request,
                              ::tmapreduce::WorkerReplyMsg* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(1),
                       controller, request, response, done);
}
void WorkerService_Stub::PrepareMap(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::tmapreduce::MapJobMsg* request,
                              ::tmapreduce::WorkerReplyMsg* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(2),
                       controller, request, response, done);
}
void WorkerService_Stub::PrepareReduce(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::tmapreduce::ReduceJobMsg* request,
                              ::tmapreduce::WorkerReplyMsg* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(3),
                       controller, request, response, done);
}
void WorkerService_Stub::Start(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const PROTOBUF_NAMESPACE_ID::Empty* request,
                              ::tmapreduce::WorkerReplyMsg* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(4),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace tmapreduce
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::tmapreduce::WorkerReplyMsg* Arena::CreateMaybeMessage< ::tmapreduce::WorkerReplyMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tmapreduce::WorkerReplyMsg >(arena);
}
template<> PROTOBUF_NOINLINE ::tmapreduce::PrepareMsg* Arena::CreateMaybeMessage< ::tmapreduce::PrepareMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tmapreduce::PrepareMsg >(arena);
}
template<> PROTOBUF_NOINLINE ::tmapreduce::MapJobMsg_MapKV* Arena::CreateMaybeMessage< ::tmapreduce::MapJobMsg_MapKV >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tmapreduce::MapJobMsg_MapKV >(arena);
}
template<> PROTOBUF_NOINLINE ::tmapreduce::MapJobMsg* Arena::CreateMaybeMessage< ::tmapreduce::MapJobMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tmapreduce::MapJobMsg >(arena);
}
template<> PROTOBUF_NOINLINE ::tmapreduce::ReduceJobMsg_ReduceKV* Arena::CreateMaybeMessage< ::tmapreduce::ReduceJobMsg_ReduceKV >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tmapreduce::ReduceJobMsg_ReduceKV >(arena);
}
template<> PROTOBUF_NOINLINE ::tmapreduce::ReduceJobMsg* Arena::CreateMaybeMessage< ::tmapreduce::ReduceJobMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tmapreduce::ReduceJobMsg >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
